#!/system/bin/sh
# ASB active-use efficiency envelope.
#
# Generates a small, inspectable derived policy from *observed* capabilities.
# It contains percentages and uclamp deltas only: no voltage control, no fixed CPU/GPU
# frequencies and no vendor thermal trip-point changes. The native governor still requires
# its existing thermal-budget gate, multi-sensor evidence and dwell protection before using it.
#
# Unknown hardware is deliberately a transparent no-op. The named entries below cover the
# supported Snapdragon families only, while topology/GPU/thermal facts must also be present.

ASB_DIR="${ASB_CONFIG_STATE:-/data/adb/asb}"
CAPS="$ASB_DIR/device_caps.env"
OUT="$ASB_DIR/active_efficiency.env"
TMP="$OUT.tmp.$$"
mkdir -p "$ASB_DIR" 2>/dev/null || exit 0

_cget() { grep -E "^$1=" "$CAPS" 2>/dev/null | head -1 | sed 's/^[^=]*=//' | tr -d '\r'; }
_num() { case "$1" in ''|*[!0-9-]*) return 1 ;; *) return 0 ;; esac; }
_atomic() {
  chmod 0644 "$TMP" 2>/dev/null
  mv -f "$TMP" "$OUT" 2>/dev/null || { rm -f "$TMP" 2>/dev/null; return 1; }
}

_soc="$(_cget soc_platform)"
[ -n "$_soc" ] || _soc="$(getprop ro.board.platform 2>/dev/null)"
_soc="$(printf '%s' "$_soc" | tr '[:upper:]' '[:lower:]' | tr -d ' \r\n')"
_policies="$(_cget cpu_policy_count)"
_gpu="$(_cget gpu_backend)"
_zones="$(_cget thermal_zone_count)"

_status="generic"
_reason="unknown_soc_or_capability"
_tier="generic"
_light=0
_moderate=0
_severe=0
_gpu_bonus=0
_bg_moderate=0
_bg_severe=0

# A physical SoC name alone is not enough: missing topology, GPU or thermal information keeps
# the policy inactive. This avoids guessing on ports/custom kernels and preserves stock ASB.
if _num "$_policies" && _num "$_zones" && [ "$_policies" -ge 2 ] 2>/dev/null && \
   [ "$_zones" -gt 0 ] 2>/dev/null && [ "$_gpu" != "" ] && [ "$_gpu" != "none" ]; then
  case "$_soc" in
    sm8750*|sun*)
      # Reference family: smallest extra nudge. It only engages after ASB thermal budget does.
      _status="active"; _reason="supported_sm8750"; _tier="sm8750"
      _light=1; _moderate=2; _severe=1; _gpu_bonus=1; _bg_moderate=48; _bg_severe=96
      ;;
    sm8650*|pineapple*|lanai*)
      # 8 Gen 3 family: retain interactive prime bounds, cool through steady-state ceiling
      # restraint and background uclamp instead of a universal frequency cap.
      _status="active"; _reason="supported_sm8650"; _tier="sm8650"
      _light=1; _moderate=3; _severe=2; _gpu_bonus=2; _bg_moderate=64; _bg_severe=128
      ;;
    sm8550*|kalama*)
      # 8 Gen 2 family: conservative envelope; background work is reduced before foreground
      # caps, and GPU trim remains above the user-configured floor.
      _status="active"; _reason="supported_sm8550"; _tier="sm8550"
      _light=1; _moderate=2; _severe=2; _gpu_bonus=1; _bg_moderate=64; _bg_severe=112
      ;;
    *)
      _reason="unknown_soc"
      ;;
  esac
else
  _reason="missing_cpu_gpu_or_thermal_capability"
fi

{
  echo "# active_efficiency.env — generated by ASB; do not edit"
  echo "# schema=1; reversible percent/uclamp policy only; vendor Thermal HAL remains authoritative"
  echo "schema=1"
  echo "status=$_status"
  echo "reason=$_reason"
  echo "soc=$_soc"
  echo "tier=$_tier"
  echo "cpu_policy_count=${_policies:-0}"
  echo "gpu_backend=${_gpu:-none}"
  echo "thermal_zone_count=${_zones:-0}"
  echo "budget_light_bonus_pct=$_light"
  echo "budget_moderate_bonus_pct=$_moderate"
  echo "budget_severe_bonus_pct=$_severe"
  echo "gpu_idle_trim_bonus_pct=$_gpu_bonus"
  echo "bg_uclamp_moderate_delta=$_bg_moderate"
  echo "bg_uclamp_severe_delta=$_bg_severe"
} > "$TMP" 2>/dev/null && _atomic
