BATTERY_CPU_MIN_LITTLE=307200
BATTERY_CPU_MIN_BIG=614400
BATTERY_CPU_CAP_LITTLE=921600
BATTERY_CPU_CAP_BIG=921600
BATTERY_CPU_MAX_LITTLE=1670400
BATTERY_CPU_MAX_BIG=1862400
BATTERY_GPU_MAX_PCT=44
BATTERY_FLOOR_GPU_MAX_PCT=40
BATTERY_FLOOR_GPU_MIN_PCT=0
BATTERY_CEIL_GPU_MIN_PCT=0
BATTERY_FLOOR_RAVG_TICKS=8
BATTERY_CEIL_RAVG_TICKS=8
BATTERY_FLOOR_IDLE_ENOUGH=95
BATTERY_CEIL_IDLE_ENOUGH=95
BATTERY_FLOOR_UCLAMP_TOP=35
BATTERY_FLOOR_UCLAMP_BG=25
BATTERY_CEIL_UCLAMP_TOP=50
BATTERY_CEIL_UCLAMP_BG=40
BALANCED_CPU_MIN_LITTLE=787200
BALANCED_CPU_MIN_BIG=883200
BALANCED_CPU_CAP_LITTLE=1190400
BALANCED_CPU_CAP_BIG=1881600
BALANCED_CPU_MAX_LITTLE=3302400
BALANCED_CPU_MAX_BIG=3974400
BALANCED_GPU_MAX_PCT=85
BALANCED_FLOOR_GPU_MAX_PCT=42
BALANCED_FLOOR_GPU_MIN_PCT=0
BALANCED_CEIL_GPU_MIN_PCT=0
BALANCED_FLOOR_RAVG_TICKS=4
BALANCED_CEIL_RAVG_TICKS=3
BALANCED_FLOOR_IDLE_ENOUGH=50
BALANCED_CEIL_IDLE_ENOUGH=45
BALANCED_FLOOR_UCLAMP_TOP=50
BALANCED_FLOOR_UCLAMP_BG=25
BALANCED_CEIL_UCLAMP_TOP=85
BALANCED_CEIL_UCLAMP_BG=35
PERFORMANCE_CPU_MIN_LITTLE=1190400
PERFORMANCE_CPU_MIN_BIG=921600
PERFORMANCE_CPU_CAP_LITTLE=2400000
PERFORMANCE_CPU_CAP_BIG=2745600
PERFORMANCE_CPU_MAX_LITTLE=3724800
PERFORMANCE_CPU_MAX_BIG=4704000
PERFORMANCE_GPU_MAX_PCT=100
PERFORMANCE_FLOOR_GPU_MAX_PCT=85
PERFORMANCE_FLOOR_GPU_MIN_PCT=8
PERFORMANCE_CEIL_GPU_MIN_PCT=20
PERFORMANCE_FLOOR_RAVG_TICKS=2
PERFORMANCE_CEIL_RAVG_TICKS=2
PERFORMANCE_FLOOR_IDLE_ENOUGH=10
PERFORMANCE_CEIL_IDLE_ENOUGH=8
PERFORMANCE_FLOOR_UCLAMP_TOP=68
PERFORMANCE_FLOOR_UCLAMP_BG=35
PERFORMANCE_CEIL_UCLAMP_TOP=84
PERFORMANCE_CEIL_UCLAMP_BG=62
