#!/system/bin/sh

# Arabic installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank.

# Arabic is right-to-left. These strings are only ever printed by ui_print into the
# root manager's console, which lays out text itself - there is no layout of ours to
# mirror. The WebUI is a different matter and sets dir="rtl" separately.

ASB_HINT="[VOL+] تفعيل | [VOL-] تخطي"
ASB_TIMEOUT="! انتهى الوقت (10 ثوانٍ). تم إلغاء التثبيت."
ASB_HELP="VOL+ = تفعيل  |  VOL- = تخطي  |  مهلة 10 ثوانٍ = إلغاء"
ASB_SEC_DEVICE="الجهاز"
ASB_SEC_CONFIG="الإعدادات"
ASB_SEC_GOVERNOR="المنظّم"
ASB_SEC_AUDIO="الصوت"
ASB_SEC_BT="بلوتوث"
ASB_SEC_CAMERA="الكاميرا"
ASB_SEC_MEDIA="الوسائط"
ASB_SEC_PERF="الأداء"
ASB_SEC_LOCATION="الموقع"
ASB_SEC_WIFI="واي فاي"
ASB_SEC_SYSTEM="النظام"
ASB_SEC_CATEGORIES="المكونات المُعَدّة"
ASB_L_MIRROR_AUDIO_TOTAL="تم نسخ %s ملف إعداد صوت من %s مجلد device-native — ASB يعدّل النسخ، لا النظام"
ASB_SEC_INSTALLING="جارٍ التثبيت لـ"
ASB_SEC_BUILDING="إنشاء طبقة من ملفات هذا الهاتف الأصلية"
ASB_SEC_NOTICE="ما الذي ستلاحظه"
ASB_SEC_DSP="محرك DSP"
ASB_SEC_DISPLAY="الشاشة"
ASB_SEC_HAPTICS="الاهتزاز"
ASB_SEC_BATTERY="البطارية"
ASB_SEC_MEMORY="الذاكرة"
ASB_L_NOTICE_FOOT1="كل ما سبق قابل للتعديل في واجهة الويب، وإعادة التشغيل"
ASB_L_NOTICE_FOOT2="تطبّق الأجزاء التي تحتاج إليها."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="تم تثبيت AutoSystemBoost"
ASB_DONE_MSG="أعد تشغيل الهاتف لتطبيق التغييرات."
ASB_D_IDENTIFIED="تم التعرّف"
ASB_D_SOC="المعالج"
ASB_D_MANAGER="مدير الروت"
ASB_D_FULL_PKG="حزمة device-native كاملة لـ OnePlus 15"
ASB_D_STOCK_ANALYSIS="تحليل ملفات المصنع:"
ASB_D_FRESH="تثبيت جديد — الإعدادات الافتراضية"
ASB_D_MIGRATED="تم نقل إعدادات الصوت"
ASB_D_LEARN_RESET="تمت إعادة ضبط التعلّم؛ الإعدادات وبيانات الجهاز محفوظة"
ASB_D_GOV="خدمة governor أصلية بلغة C"
ASB_D_DSP_ENGINE="محرك DSP"
ASB_D_DSP_GAIN="التضخيم"
ASB_D_DSP_CHAIN="ضاغط بركبة ناعمة -> makeup gain -> محدّد ذروة (بلا تقطيع)"
ASB_D_DSP_STAGED="المكتبة جاهزة لـ"
ASB_D_DSP_OFF="المكتبة جاهزة، التأثير متوقف"
ASB_D_DSP_REG="التأثير مسجّل في"
ASB_D_DSP_REG_TAIL="ملف audio_effects_config"
ASB_D_LOUD="صوت الوسائط"
ASB_D_LOUD_AT="عند مستوى صوت متوسط"
ASB_D_LOUD_NOTE="منحنيات الموسيقى فقط؛ المنبهات والنغمات دون تغيير؛ لا يُرفع 100% أبدًا"
ASB_D_MIXER="المازج"
ASB_D_MIXER_TAIL="ملف مضبوط — الصوت الرقمي 84->88"
ASB_D_MIXER_AGGR="DAC من الفئة Class-H، وضع HPH HIFI، الضاغط الموسّع متوقف (قوي)"
ASB_D_MIXER_STD="EQ مسطّح، DAC من الفئة Class-H"
ASB_D_OVERLAY="تم تعديل الـ overlay في مكانه (EQ / الصوت / hi-res / الترميزات)"
ASB_D_CAM_TONE="لون الكاميرا: نسخة من device-stock"
ASB_D_CAM_AGGR_INJ="تم تطبيق لون كاميرا قوي (بما في ذلك المفاتيح المضافة)"
ASB_D_CAM_AGGR_EXIST="تم تطبيق لون كاميرا قوي (المفاتيح الموجودة فقط)"
ASB_D_CAM_STOCK="الكاميرا على إعداد المصنع (تم تخطي محرك التعديلات)"
ASB_D_RETOUCH="تطبيقات التجميل"
ASB_D_MEDIA_LIFT="تم رفع معدل بت الفيديو في"
ASB_D_MEDIA_TAIL="ملف device-native"
ASB_D_PERF="تم ضبط إعدادات perf"
ASB_D_PERF_TAIL="مهلات التعزيز، game config"
ASB_D_FILES="ملفات"
ASB_I_AFX_LIBS="مكتبات الصوت الأصلية موجودة (device-native)"
ASB_D_GPS="تم ضبط GPS/A-GPS"
ASB_D_WIFI_OK="تم تعديل إعداد Wi-Fi من نوع WCNSS (device-native)"
ASB_D_WIFI_NONE="لم يُعثر على إعداد WCNSS — Wi-Fi على إعداد المصنع"
ASB_D_BT="الصوت المطلق للبلوتوث: متوقف (الهاتف يتحكم في التضخيم)"
ASB_D_BT_NOTE="(السماعة تحتفظ بمستواها؛ اختر 'stock' إذا كان صوت البلوتوث منخفضًا)"
ASB_D_BLUR="تم إيقاف التمويه عبر system.prop (بعد إعادة التشغيل)"
ASB_D_BOUNDS="حدود device-adaptive: مفعّلة (OP15 — مطابقة لضبط المصنع)"
ASB_L_MIRROR_AUDIO="تم نسخ %s ملف إعدادات صوت — ASB يعدّل النسخ، لا النظام"
ASB_L_MIRROR_CAMERA="تم نسخ %s ملف إعدادات كاميرا — ASB يعدّل النسخ، لا النظام"
ASB_L_MIRROR_SYSTEM="تم نسخ %s ملف إعدادات نظام — ASB يعدّل النسخ، لا النظام"
ASB_L_CAM_TUNING="الكاميرا: ضبط الصورة جاهز (اللون، التفاصيل، الحدّة)"
ASB_L_CAM_BEAUTY="الكاميرا: ملف التجميل جاهز (إعدادات لكل تطبيق)"
ASB_L_CAM_OTHER="الكاميرا: %s جاهز"
ASB_L_CAM_PREPARED="الكاميرا: تم تجهيز %s من نسخة المصنع"
ASB_L_CAM_GRADED="معالجة الكاميرا: المستوى %s مطبّق على %s ملف — التشبّع، تفاصيل الذكاء الاصطناعي، الحدّة"
ASB_L_TW_HIFI="الصوت: سلسلة hi-fi — ضغط الشركة المصنعة متوقف، EQ مسطّح"
ASB_L_TW_EQC="الصوت: مضبوط لمعادلات الصوت الخارجية (ViPER وما يشبهه)"
ASB_L_TW_LOUD="مستوى الصوت: المستوى المريح يتحقق في موضع أدنى من المنزلق"
ASB_L_TW_DSP="DSP: تضخيم حقيقي بمقدار +%s dB مع محدّد ذروة"
ASB_L_TW_CAM="الكاميرا: مستوى المعالجة %s — رفع اللون وتفاصيل الذكاء الاصطناعي والحدّة"
ASB_L_TW_PORTRAIT="الكاميرا: ذكاء البورتريه مفعّل (متوقف افتراضيًا) — تفاصيل أكثر في الوجوه"
ASB_L_TW_VIB_OFF="الاهتزاز: متوقف"
ASB_L_TW_VIB="الاهتزاز: المستوى %s/10 على مقياس الشركة المصنعة"
ASB_L_TW_BLUR="الشاشة: التمويه متوقف — حمل أقل على GPU، خلفيات صلبة"
ASB_L_TW_AUTOBAT="البطارية: تنتقل إلى ملف البطارية عند انخفاض الشحن وتعود بعد الشحن"
ASB_L_TW_COOL="الألعاب: الكبح الحراري يبدأ مبكرًا، فيبقى الهاتف أبرد"
ASB_L_DSP_REG_N="مسجّل في %s ملف إعداد صوت"
ASB_L_DSP_ODM="مسجّل في الإعداد الذي يقرؤه Android فعلًا"
ASB_L_CAM_QUEUED="الكاميرا: سيتم ربط %s إعداد عند الإقلاع"
ASB_L_MMFEED_READY="قياس الوسائط المتعددة عن بُعد: التصحيح جاهز — متوقف افتراضيًا، يُفعّل من WebUI (النظام)"
ASB_L_CALLREC_READY="تسجيل المكالمات: التصحيح جاهز (%s ملف) — متوقف افتراضيًا، يُفعّل من WebUI (النظام)"
ASB_L_VIB_SET="القوة %s/10 على مقياس الشركة المصنعة، طُبّقت فورًا"
ASB_L_VIB_TOUCH="استجابة اللمس %s/10، مضبوطة على حدة"
ASB_L_BAT_AUTO="تنتقل إلى البطارية عند انخفاض الشحن وتعود بعد الشحن"
ASB_L_BAT_CHARGE="هامش أكبر عند الشحن والجهاز بارد، وأقل عند السخونة"
ASB_L_BAT_COOL="في الألعاب يبدأ الكبح الحراري مبكرًا، فيبقى الهاتف أبرد"
ASB_L_MEM_TRIM="تنظيف الخلفية: %s"
ASB_L_CAM_BASE_FIX1="مرجع الكاميرا من إصدار أقدم كان معالجًا مسبقًا — تم حذفه"
ASB_L_CAM_BASE_FIX2="سيُلتقط من جديد من نسخة المصنع بعد إعادة التشغيل هذه"
ASB_L_CAM_LIVE_DIRTY1="ألوان الكاميرا على الجهاز معالجة بإصدار سابق — يتم تخطيها"
ASB_L_CAM_LIVE_DIRTY2="تُثبَّت هذه النسخة دون ألوان الكاميرا؛ بعد إعادة التشغيل ثبّت ASB مرة أخرى فقط (لا حاجة لتعطيله) — يُلتقط المرجع حينها من الملف الأصلي"
ASB_L_FIX_SYSSYS="تمت إزالة مسار system/system خاطئ من إصدار سابق"
ASB_I_OEM_KEPT="تم حفظ مفاتيح OEM الحالية"
ASB_I_PROFILE_KEPT="تم الإبقاء على ملف الطاقة"
ASB_I_PACK_CERT="حزمة الجهاز معتمدة لهذا الإصدار من البرنامج الثابت"
ASB_I_DSP_ABI="تم اختيار التأثير لهذا الجهاز"
ASB_I_DSP_ATTACH="الـ attacher جاهز (ينشئ التأثير على المزج العام)"
ASB_I_CAM_TUNING="ضبط الكاميرا: المستوى %s، مطبّق على %s ملف"
ASB_I_RETOUCH_OK="تم التحقق من حزمة الكاميرا النهائية"
ASB_I_HP_LIMIT="تمت إزالة محدّد صوت السماعات — احمِ سمعك"
ASB_INSTALL_WEBUI_FIRST="جميع المكونات جاهزة؛ التعديلات الاختيارية تبقى على إعداد المصنع."
ASB_INSTALL_WEBUI_HINT="بعد إعادة التشغيل افتح WebUI وفعّل ما تريده فقط."
ASB_SUM_PROFILE="الملف"
ASB_SUM_NOTES="يستحق القراءة"
ASB_SUM_WEBUI="الإعدادات: WebUI الخاصة بالوحدة، بعد إعادة التشغيل"
