#!/system/bin/sh

ASB_HINT="[VOL+] Enable | [VOL-] Skip"
ASB_TIMEOUT="! Time is up (10 seconds). Installation canceled."

ASB_HELP="VOL+ = enable  |  VOL- = skip  |  10s timeout = cancel"

ASB_CFG_FOUND_TITLE="Saved configuration found"
ASB_CFG_FOUND_HINT="VOL+ = use saved  |  VOL- = re-select categories"
ASB_CFG_USING_SAVED="Using saved configuration from:"
ASB_CFG_RESELECT="Re-selecting categories..."
ASB_CFG_SAVED_TO="Configuration saved to:"

ASB_MENU_AUDIO=" 1) AUDIO (HAL/Codecs/Effects/Mixers)"
ASB_MENU_BT="2) Bluetooth (A2DP/LE Audio/Codecs)"
ASB_MENU_CAMERA="3) CAMERA (Photo/Video)"
ASB_MENU_CPU="4) CPU (Scheduler/Frequencies)"
ASB_MENU_VM="5) VM (Memory/Dirty/Swappiness)"
ASB_MENU_NET="6) NET (TCP/Qdisc/Buffers/Queues)"
ASB_MENU_WIFI="7) WiFi (Scan/Sleep)"
ASB_MENU_GPS="8) GPS (GNSS)"
ASB_MENU_KERNEL="9) KERNEL (printk/perf)"
ASB_MENU_LOG="10) LOGS (Services/Noise)"
ASB_MENU_RADIO_IMS="11) RADIO/IMS (VoLTE/VoNR/IMS auth)"
ASB_MENU_DISPLAY="12) DISPLAY (CABL/DPPS/Backlight)"
ASB_MENU_FPS="13) FPS (Frame rate caps/Recorder)"
ASB_MENU_SECURITY="14) SECURITY (Perf events/Snapshots)"
ASB_MENU_BG_TRIM="15) BG_TRIM (Telemetry + Wakeups + Doze)"

ASB_DONE_TITLE="ASB"
ASB_DONE_MSG="Module installed! Reboot required."

# --- install progress section headers (V60) ---
ASB_SEC_DEVICE="DEVICE"
ASB_SEC_CONFIG="CONFIG"
ASB_SEC_GOVERNOR="GOVERNOR"
ASB_SEC_AUDIO="AUDIO"
ASB_SEC_CAMERA="CAMERA"
ASB_SEC_MEDIA="MEDIA"
ASB_SEC_PERF="PERFORMANCE"
ASB_SEC_LOCATION="LOCATION"
ASB_SEC_WIFI="WI-FI"
ASB_SEC_SYSTEM="SYSTEM"
ASB_SEC_CATEGORIES="ENABLED CATEGORIES"
ASB_SEC_INSTALLING="installing for"
ASB_SEC_BUILDING="building a device-native overlay from this phone's own stock files"

# --- install progress detail lines (V60) ---
ASB_D_IDENTIFIED="identified"
ASB_D_SOC="SoC"
ASB_D_MANAGER="root manager"
ASB_D_FULL_PKG="full OnePlus 15 device-native package"
ASB_D_STOCK_ANALYSIS="stock-file analysis:"
ASB_D_FRESH="fresh install — shipped defaults"
ASB_D_MIGRATED="audio settings migrated"
ASB_D_LEARN_RESET="learning reset; settings and device data preserved"
ASB_D_GOV="native C governor daemon"
ASB_D_DSP_ENGINE="DSP engine"
ASB_D_DSP_GAIN="gain"
ASB_D_DSP_CHAIN="soft-knee compressor -> makeup gain -> peak limiter (no clip)"
ASB_D_DSP_STAGED="library staged for"
ASB_D_DSP_OFF="library staged, effect off"
ASB_D_DSP_REG="effect registered in"
ASB_D_DSP_REG_TAIL="audio_effects_config file(s)"
ASB_D_LOUD="media loudness"
ASB_D_LOUD_AT="at mid volume"
ASB_D_LOUD_NOTE="music curves only; alarms/ringtones untouched; 100% never raised"
ASB_D_MIXER="mixer"
ASB_D_MIXER_TAIL="file(s) tuned — digital vol 84->88"
ASB_D_MIXER_AGGR="Class-H DAC, HPH HIFI mode, compander off (aggressive)"
ASB_D_MIXER_STD="flat EQ, Class-H DAC"
ASB_D_OVERLAY="overlay patched in place (EQ / volume / hi-res / codecs)"
ASB_D_CAM_TONE="camera tone: cloned device-stock"
ASB_D_CAM_AGGR_INJ="camera aggressive tone applied (incl. injected keys)"
ASB_D_CAM_AGGR_EXIST="camera aggressive tone applied (existing keys only)"
ASB_D_CAM_STOCK="camera kept stock (tweak engine skipped)"
ASB_D_RETOUCH="retouch apps"
ASB_D_MEDIA_LIFT="video bitrate lifted in"
ASB_D_MEDIA_TAIL="device-native file(s)"
ASB_D_PERF="perf configs tuned"
ASB_D_PERF_TAIL="boost timeouts, game config"
ASB_D_GPS="GPS/A-GPS tuned"
ASB_D_WIFI_OK="WCNSS Wi-Fi config patched (device-native)"
ASB_D_WIFI_NONE="no device WCNSS config found — Wi-Fi left stock"
ASB_D_BT="BT absolute volume: disabled (phone drives gain)"
ASB_D_BT_NOTE="(headset drives its own level; use 'stock' if BT starts quiet)"
ASB_D_BLUR="blur disabled via system.prop (applies after reboot)"
ASB_D_BOUNDS="device-adaptive bounds: ON (OP15 — matches shipped tuning)"
