#!/system/bin/sh

# German installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank. The strings
# chosen are the ones a user actually reads during an install - prompts, section
# headings and the closing note. Per-tweak detail lines remain English until someone
# who speaks the language writes them; a machine-translated technical claim that reads
# fluently and says the wrong thing is worse than English.

ASB_HINT="[VOL+] Aktivieren | [VOL-] Überspringen"
ASB_TIMEOUT="! Zeit abgelaufen (10 Sekunden). Installation abgebrochen."
ASB_HELP="VOL+ = aktivieren  |  VOL- = überspringen  |  10s Timeout = Abbruch"
ASB_SEC_DEVICE="GERÄT"
ASB_SEC_CONFIG="KONFIGURATION"
ASB_SEC_GOVERNOR="GOVERNOR"
ASB_SEC_AUDIO="AUDIO"
ASB_SEC_BT="BLUETOOTH"
ASB_SEC_CAMERA="KAMERA"
ASB_SEC_MEDIA="MEDIEN"
ASB_SEC_PERF="LEISTUNG"
ASB_SEC_LOCATION="STANDORT"
ASB_SEC_WIFI="WLAN"
ASB_SEC_SYSTEM="SYSTEM"
ASB_SEC_CATEGORIES="VORBEREITETE KOMPONENTEN"
ASB_L_MIRROR_AUDIO_TOTAL="%s Audio-Konfigurationsdatei(en) aus %s device-native Ordner(n) kopiert — ASB bearbeitet die Kopien, nie das System"
ASB_SEC_INSTALLING="Installation für"
ASB_SEC_BUILDING="Overlay wird aus den Originaldateien dieses Geräts erstellt"
ASB_SEC_NOTICE="WAS SIE BEMERKEN WERDEN"
ASB_SEC_DSP="DSP-ENGINE"
ASB_SEC_DISPLAY="ANZEIGE"
ASB_SEC_HAPTICS="VIBRATION"
ASB_SEC_BATTERY="AKKU"
ASB_SEC_MEMORY="SPEICHER"
ASB_L_NOTICE_FOOT1="Alles davon ist in der WebUI einstellbar; ein Neustart"
ASB_L_NOTICE_FOOT2="aktiviert die Teile, die einen brauchen."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="AutoSystemBoost installiert"
ASB_DONE_MSG="Telefon neu starten, damit alles wirksam wird."
ASB_D_IDENTIFIED="erkannt"
ASB_D_SOC="Prozessor"
ASB_D_MANAGER="Root-Manager"
ASB_D_FULL_PKG="vollständiges device-native Paket für OnePlus 15"
ASB_D_STOCK_ANALYSIS="Analyse der Stock-Dateien:"
ASB_D_FRESH="Neuinstallation — Standardeinstellungen"
ASB_D_MIGRATED="Audioeinstellungen übernommen"
ASB_D_LEARN_RESET="Lernen zurückgesetzt; Einstellungen und Gerätedaten bleiben erhalten"
ASB_D_GOV="nativer C-Governor-Dienst"
ASB_D_DSP_ENGINE="DSP-Engine"
ASB_D_DSP_GAIN="Verstärkung"
ASB_D_DSP_CHAIN="Soft-Knee-Kompressor -> Makeup-Gain -> Peak-Limiter (kein Clipping)"
ASB_D_DSP_STAGED="Bibliothek bereit für"
ASB_D_DSP_OFF="Bibliothek bereit, Effekt aus"
ASB_D_DSP_REG="Effekt registriert in"
ASB_D_DSP_REG_TAIL="audio_effects_config-Datei(en)"
ASB_D_LOUD="Medienlautstärke"
ASB_D_LOUD_AT="bei mittlerer Lautstärke"
ASB_D_LOUD_NOTE="nur Musikkurven; Wecker und Klingeltöne unverändert; 100% wird nie angehoben"
ASB_D_MIXER="Mixer"
ASB_D_MIXER_TAIL="Datei(en) angepasst — digitale Lautstärke 84->88"
ASB_D_MIXER_AGGR="Class-H-DAC, HPH-HIFI-Modus, Kompander aus (aggressiv)"
ASB_D_MIXER_STD="flacher EQ, Class-H-DAC"
ASB_D_OVERLAY="Overlay direkt gepatcht (EQ / Lautstärke / Hi-Res / Codecs)"
ASB_D_CAM_TONE="Kameraton: device-stock geklont"
ASB_D_CAM_AGGR_INJ="aggressiver Kameraton angewendet (inkl. ergänzter Schlüssel)"
ASB_D_CAM_AGGR_EXIST="aggressiver Kameraton angewendet (nur vorhandene Schlüssel)"
ASB_D_CAM_STOCK="Kamera bleibt Stock (Tweak-Engine übersprungen)"
ASB_D_RETOUCH="Retusche-Apps"
ASB_D_MEDIA_LIFT="Video-Bitrate angehoben in"
ASB_D_MEDIA_TAIL="device-native Datei(en)"
ASB_D_PERF="Perf-Konfigurationen angepasst"
ASB_D_PERF_TAIL="Boost-Timeouts, Game-Config"
ASB_D_FILES="Datei(en)"
ASB_I_AFX_LIBS="Standard-Lautstärkebibliotheken vorhanden (device-native)"
ASB_D_GPS="GPS/A-GPS angepasst"
ASB_D_WIFI_OK="WCNSS-WLAN-Konfiguration gepatcht (device-native)"
ASB_D_WIFI_NONE="keine WCNSS-Konfiguration gefunden — WLAN bleibt Stock"
ASB_D_BT="BT-Absolutlautstärke: aus (das Telefon steuert die Verstärkung)"
ASB_D_BT_NOTE="(das Headset behält seinen Pegel; 'stock' wählen, wenn BT leise ist)"
ASB_D_BLUR="Unschärfe über system.prop aus (wirkt nach dem Neustart)"
ASB_D_BOUNDS="device-adaptive Grenzen: AN (OP15 — entspricht der Werksabstimmung)"
ASB_L_MIRROR_AUDIO="%s Audio-Einstellungsdatei(en) kopiert — ASB bearbeitet die Kopien, nie das System"
ASB_L_MIRROR_CAMERA="%s Kamera-Einstellungsdatei(en) kopiert — ASB bearbeitet die Kopien, nie das System"
ASB_L_MIRROR_SYSTEM="%s System-Einstellungsdatei(en) kopiert — ASB bearbeitet die Kopien, nie das System"
ASB_L_CAM_TUNING="Kamera: Bildabstimmung bereit (Farbe, Details, Schärfe)"
ASB_L_CAM_BEAUTY="Kamera: Retusche-Profil bereit (Einstellungen pro App)"
ASB_L_CAM_OTHER="Kamera: %s bereit"
ASB_L_CAM_PREPARED="Kamera: %s aus der Stock-Kopie vorbereitet"
ASB_L_CAM_GRADED="Kamera-Grading: Stufe %s auf %s Datei(en) angewendet — Sättigung, KI-Details, Schärfe"
ASB_L_TW_HIFI="Audio: Hi-Fi-Kette — Hersteller-Kompression aus, flacher EQ"
ASB_L_TW_EQC="Audio: auf externe Equalizer abgestimmt (ViPER und ähnliche)"
ASB_L_TW_LOUD="Lautstärke: angenehmer Pegel schon weiter unten auf dem Regler"
ASB_L_TW_DSP="DSP: echte Verstärkung +%s dB, mit Peak-Limiter"
ASB_L_TW_CAM="Kamera: Grading-Stufe %s — Farbe, KI-Details und Schärfe angehoben"
ASB_L_TW_PORTRAIT="Kamera: Porträt-KI an (ab Werk aus) — mehr Details in Gesichtern"
ASB_L_TW_VIB_OFF="Vibration: aus"
ASB_L_TW_VIB="Vibration: Stufe %s/10 auf der Herstellerskala"
ASB_L_TW_BLUR="Anzeige: Unschärfe aus — weniger GPU-Last, feste Hintergründe"
ASB_L_TW_AUTOBAT="Akku: wechselt bei niedrigem Stand ins Akku-Profil und nach dem Laden zurück"
ASB_L_TW_COOL="Spiele: thermische Zurückhaltung setzt früher ein, das Telefon bleibt kühler"
ASB_L_DSP_REG_N="in %s Audio-Konfigurationsdatei(en) registriert"
ASB_L_DSP_ODM="registriert in der Konfiguration, die Android tatsächlich liest"
ASB_L_CAM_QUEUED="Kamera: %s Konfiguration(en) werden beim Start eingebunden"
ASB_L_MMFEED_READY="Multimedia-Telemetrie: Patch bereit — standardmäßig aus, in der WebUI (System) schaltbar"
ASB_L_CALLREC_READY="Anrufaufzeichnung: Patch bereit (%s Datei(en)) — standardmäßig aus, in der WebUI (System) schaltbar"
ASB_L_VIB_SET="Stärke %s/10 auf der Herstellerskala, sofort angewendet"
ASB_L_VIB_TOUCH="Berührungsfeedback %s/10, separat eingestellt"
ASB_L_BAT_AUTO="wechselt bei niedrigem Stand zu Akku und nach dem Laden zurück"
ASB_L_BAT_CHARGE="mehr Reserve beim kühlen Laden, weniger bei Wärme"
ASB_L_BAT_COOL="in Spielen greift der Wärmeschutz früher, das Telefon bleibt kühler"
ASB_L_MEM_TRIM="Hintergrundbereinigung: %s"
ASB_L_CAM_BASE_FIX1="Kamera-Referenz aus einem älteren Build war bereits bearbeitet — verworfen"
ASB_L_CAM_BASE_FIX2="sie wird nach diesem Neustart neu aus der Stock-Kopie erfasst"
ASB_L_CAM_LIVE_DIRTY1="Kamerafarbe auf dem Gerät stammt von einem früheren Build — wird übersprungen"
ASB_L_CAM_LIVE_DIRTY2="diese Installation lässt die Kamerafarbe aus; nach dem Neustart ASB einfach noch einmal installieren (Deaktivieren nicht nötig) — die Referenz wird dann aus der Originaldatei erfasst"
ASB_L_FIX_SYSSYS="fehlerhaften Pfad system/system aus einem früheren Build entfernt"
ASB_I_OEM_KEPT="aktuelle OEM-Schalter gespeichert"
ASB_I_PROFILE_KEPT="Energieprofil beibehalten"
ASB_I_PACK_CERT="Gerätepaket für diese Firmware zertifiziert"
ASB_I_DSP_ABI="Effekt für dieses Gerät gewählt"
ASB_I_DSP_ATTACH="Attacher bereit (erzeugt den Effekt auf dem globalen Mix)"
ASB_I_CAM_TUNING="Kamera-Abstimmung: Stufe %s, auf %s Datei(en) angewendet"
ASB_I_RETOUCH_OK="finales Kamerapaket geprüft"
ASB_I_HP_LIMIT="Kopfhörer-Lautstärkebegrenzung entfernt — schützen Sie Ihr Gehör"
ASB_INSTALL_WEBUI_FIRST="Alle Komponenten vorbereitet; optionale Tweaks bleiben auf Stock."
ASB_INSTALL_WEBUI_HINT="Nach dem Neustart die WebUI öffnen und nur das Gewünschte aktivieren."
ASB_SUM_PROFILE="Profil"
ASB_SUM_NOTES="Bitte lesen"
ASB_SUM_WEBUI="Einstellungen: WebUI des Moduls, nach dem Neustart"
