#!/system/bin/sh

# Indonesian installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank. The strings
# chosen are the ones a user actually reads during an install - prompts, section
# headings and the closing note. Per-tweak detail lines remain English until someone
# who speaks the language writes them; a machine-translated technical claim that reads
# fluently and says the wrong thing is worse than English.

ASB_HINT="[VOL+] Aktifkan | [VOL-] Lewati"
ASB_TIMEOUT="! Waktu habis (10 detik). Pemasangan dibatalkan."
ASB_HELP="VOL+ = aktifkan  |  VOL- = lewati  |  batas 10 detik = batal"
ASB_SEC_DEVICE="PERANGKAT"
ASB_SEC_CONFIG="KONFIGURASI"
ASB_SEC_GOVERNOR="GOVERNOR"
ASB_SEC_AUDIO="AUDIO"
ASB_SEC_BT="BLUETOOTH"
ASB_SEC_CAMERA="KAMERA"
ASB_SEC_MEDIA="MEDIA"
ASB_SEC_PERF="PERFORMA"
ASB_SEC_LOCATION="LOKASI"
ASB_SEC_WIFI="WI-FI"
ASB_SEC_SYSTEM="SISTEM"
ASB_SEC_CATEGORIES="KOMPONEN YANG DISIAPKAN"
ASB_L_MIRROR_AUDIO_TOTAL="%s file konfigurasi audio disalin dari %s folder device-native — ASB mengedit salinannya, bukan sistem"
ASB_SEC_INSTALLING="memasang untuk"
ASB_SEC_BUILDING="membangun lapisan dari berkas asli ponsel ini"
ASB_SEC_NOTICE="YANG AKAN ANDA RASAKAN"
ASB_SEC_DSP="MESIN DSP"
ASB_SEC_DISPLAY="LAYAR"
ASB_SEC_HAPTICS="GETARAN"
ASB_SEC_BATTERY="BATERAI"
ASB_SEC_MEMORY="MEMORI"
ASB_L_NOTICE_FOOT1="Semua di atas dapat diatur di WebUI, dan memulai ulang"
ASB_L_NOTICE_FOOT2="menerapkan bagian yang membutuhkannya."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="AutoSystemBoost terpasang"
ASB_DONE_MSG="Mulai ulang ponsel agar perubahan diterapkan."
ASB_D_IDENTIFIED="terdeteksi"
ASB_D_SOC="Prosesor"
ASB_D_MANAGER="manajer root"
ASB_D_FULL_PKG="paket device-native lengkap untuk OnePlus 15"
ASB_D_STOCK_ANALYSIS="analisis file stok:"
ASB_D_FRESH="instalasi bersih — pengaturan bawaan"
ASB_D_MIGRATED="pengaturan audio dipindahkan"
ASB_D_LEARN_RESET="pembelajaran direset; pengaturan dan data perangkat tetap tersimpan"
ASB_D_GOV="daemon governor C native"
ASB_D_DSP_ENGINE="mesin DSP"
ASB_D_DSP_GAIN="penguatan"
ASB_D_DSP_CHAIN="kompresor soft-knee -> makeup gain -> pembatas puncak (tanpa clipping)"
ASB_D_DSP_STAGED="pustaka siap untuk"
ASB_D_DSP_OFF="pustaka siap, efek mati"
ASB_D_DSP_REG="efek terdaftar di"
ASB_D_DSP_REG_TAIL="file audio_effects_config"
ASB_D_LOUD="volume media"
ASB_D_LOUD_AT="pada volume sedang"
ASB_D_LOUD_NOTE="hanya kurva musik; alarm dan nada dering tidak diubah; 100% tidak pernah dinaikkan"
ASB_D_MIXER="mixer"
ASB_D_MIXER_TAIL="file disetel — volume digital 84->88"
ASB_D_MIXER_AGGR="DAC Class-H, mode HPH HIFI, kompander mati (agresif)"
ASB_D_MIXER_STD="EQ datar, DAC Class-H"
ASB_D_OVERLAY="overlay ditambal di tempat (EQ / volume / hi-res / codec)"
ASB_D_CAM_TONE="nada kamera: device-stock disalin"
ASB_D_CAM_AGGR_INJ="nada kamera agresif diterapkan (termasuk kunci tambahan)"
ASB_D_CAM_AGGR_EXIST="nada kamera agresif diterapkan (hanya kunci yang ada)"
ASB_D_CAM_STOCK="kamera dibiarkan stok (mesin tweak dilewati)"
ASB_D_RETOUCH="aplikasi retus"
ASB_D_MEDIA_LIFT="bitrate video dinaikkan di"
ASB_D_MEDIA_TAIL="file device-native"
ASB_D_PERF="konfigurasi perf disetel"
ASB_D_PERF_TAIL="batas waktu boost, game config"
ASB_D_FILES="file"
ASB_I_AFX_LIBS="pustaka volume bawaan tersedia (device-native)"
ASB_D_GPS="GPS/A-GPS disetel"
ASB_D_WIFI_OK="konfigurasi Wi-Fi WCNSS ditambal (device-native)"
ASB_D_WIFI_NONE="konfigurasi WCNSS tidak ditemukan — Wi-Fi dibiarkan stok"
ASB_D_BT="volume absolut BT: dimatikan (penguatan diatur ponsel)"
ASB_D_BT_NOTE="(headset menjaga levelnya sendiri; pilih 'stock' jika BT terlalu pelan)"
ASB_D_BLUR="efek blur dimatikan lewat system.prop (setelah mulai ulang)"
ASB_D_BOUNDS="batas device-adaptive: AKTIF (OP15 — sama dengan setelan pabrik)"
ASB_L_MIRROR_AUDIO="%s file pengaturan audio disalin — ASB mengedit salinannya, bukan sistem"
ASB_L_MIRROR_CAMERA="%s file pengaturan kamera disalin — ASB mengedit salinannya, bukan sistem"
ASB_L_MIRROR_SYSTEM="%s file pengaturan sistem disalin — ASB mengedit salinannya, bukan sistem"
ASB_L_CAM_TUNING="Kamera: penyetelan gambar siap (warna, detail, ketajaman)"
ASB_L_CAM_BEAUTY="Kamera: profil retus siap (pengaturan per aplikasi)"
ASB_L_CAM_OTHER="Kamera: %s siap"
ASB_L_CAM_PREPARED="Kamera: %s disiapkan dari salinan stok"
ASB_L_CAM_GRADED="Pengolahan kamera: level %s diterapkan ke %s file — saturasi, detail AI, ketajaman"
ASB_L_TW_HIFI="Audio: jalur hi-fi — kompresi bawaan pabrikan mati, EQ datar"
ASB_L_TW_EQC="Audio: disetel untuk equalizer eksternal (ViPER dan sejenisnya)"
ASB_L_TW_LOUD="Volume: level nyaman tercapai lebih rendah di penggeser"
ASB_L_TW_DSP="DSP: penguatan nyata +%s dB, dengan pembatas puncak"
ASB_L_TW_CAM="Kamera: level pengolahan %s — warna, detail AI, dan ketajaman ditingkatkan"
ASB_L_TW_PORTRAIT="Kamera: AI potret aktif (bawaan mati) — lebih banyak detail pada wajah"
ASB_L_TW_VIB_OFF="Getaran: mati"
ASB_L_TW_VIB="Getaran: level %s/10 pada skala pabrikan"
ASB_L_TW_BLUR="Layar: blur mati — beban GPU lebih ringan, latar belakang solid"
ASB_L_TW_AUTOBAT="Baterai: beralih ke profil Baterai saat lemah dan kembali setelah diisi"
ASB_L_TW_COOL="Game: penahan suhu bekerja lebih awal, ponsel tetap lebih dingin"
ASB_L_DSP_REG_N="terdaftar di %s file konfigurasi audio"
ASB_L_DSP_ODM="terdaftar di konfigurasi yang benar-benar dibaca Android"
ASB_L_CAM_QUEUED="Kamera: %s konfigurasi akan ditautkan saat boot"
ASB_L_MMFEED_READY="Telemetri multimedia: patch siap — mati secara bawaan, aktifkan di WebUI (Sistem)"
ASB_L_CALLREC_READY="Perekaman panggilan: patch siap (%s file) — mati secara bawaan, aktifkan di WebUI (Sistem)"
ASB_L_VIB_SET="kekuatan %s/10 pada skala pabrikan, langsung diterapkan"
ASB_L_VIB_TOUCH="umpan balik sentuh %s/10, diatur terpisah"
ASB_L_BAT_AUTO="beralih ke Baterai saat lemah dan kembali setelah diisi"
ASB_L_BAT_CHARGE="ruang lebih saat mengisi dalam keadaan dingin, lebih sedikit saat panas"
ASB_L_BAT_COOL="di game penahan suhu bekerja lebih awal, ponsel lebih dingin"
ASB_L_MEM_TRIM="pembersihan latar belakang: %s"
ASB_L_CAM_BASE_FIX1="referensi kamera dari versi lama sudah diolah — dibuang"
ASB_L_CAM_BASE_FIX2="akan diambil ulang dari salinan stok setelah mulai ulang ini"
ASB_L_CAM_LIVE_DIRTY1="warna kamera di perangkat diolah oleh versi sebelumnya — dilewati"
ASB_L_CAM_LIVE_DIRTY2="instalasi ini melewati warna kamera; setelah mulai ulang cukup instal ASB sekali lagi (tidak perlu dinonaktifkan) — referensi lalu diambil dari file asli"
ASB_L_FIX_SYSSYS="jalur system/system yang keliru dari versi sebelumnya dihapus"
ASB_I_OEM_KEPT="sakelar OEM saat ini disimpan"
ASB_I_PROFILE_KEPT="profil daya dipertahankan"
ASB_I_PACK_CERT="paket perangkat tersertifikasi untuk firmware ini"
ASB_I_DSP_ABI="efek dipilih untuk perangkat ini"
ASB_I_DSP_ATTACH="attacher siap (membuat efek di mix global)"
ASB_I_CAM_TUNING="penyetelan kamera: level %s, diterapkan ke %s file"
ASB_I_RETOUCH_OK="paket kamera akhir terverifikasi"
ASB_I_HP_LIMIT="pembatas volume headphone dilepas — jaga pendengaran Anda"
ASB_INSTALL_WEBUI_FIRST="Semua komponen siap; tweak opsional tetap stok."
ASB_INSTALL_WEBUI_HINT="Setelah mulai ulang, buka WebUI dan aktifkan hanya yang Anda inginkan."
ASB_SUM_PROFILE="profil"
ASB_SUM_NOTES="Perlu dibaca"
ASB_SUM_WEBUI="Pengaturan: WebUI modul, setelah mulai ulang"
