#!/system/bin/sh

# Portuguese installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank. The strings
# chosen are the ones a user actually reads during an install - prompts, section
# headings and the closing note. Per-tweak detail lines remain English until someone
# who speaks the language writes them; a machine-translated technical claim that reads
# fluently and says the wrong thing is worse than English.

ASB_HINT="[VOL+] Ativar | [VOL-] Pular"
ASB_TIMEOUT="! Tempo esgotado (10 segundos). Instalação cancelada."
ASB_HELP="VOL+ = ativar  |  VOL- = pular  |  10s sem toque = cancelar"
ASB_SEC_DEVICE="DISPOSITIVO"
ASB_SEC_CONFIG="CONFIGURAÇÃO"
ASB_SEC_GOVERNOR="GOVERNADOR"
ASB_SEC_AUDIO="ÁUDIO"
ASB_SEC_BT="BLUETOOTH"
ASB_SEC_CAMERA="CÂMERA"
ASB_SEC_MEDIA="MÍDIA"
ASB_SEC_PERF="DESEMPENHO"
ASB_SEC_LOCATION="LOCALIZAÇÃO"
ASB_SEC_WIFI="WIFI"
ASB_SEC_SYSTEM="SISTEMA"
ASB_SEC_CATEGORIES="COMPONENTES PREPARADOS"
ASB_L_MIRROR_AUDIO_TOTAL="copiados %s arquivo(s) de configuração de áudio de %s pasta(s) device-native — o ASB edita as cópias, nunca o sistema"
ASB_SEC_INSTALLING="instalando para"
ASB_SEC_BUILDING="criando uma camada a partir dos arquivos originais deste telefone"
ASB_SEC_NOTICE="O QUE VOCÊ VAI NOTAR"
ASB_SEC_DSP="MOTOR DSP"
ASB_SEC_DISPLAY="TELA"
ASB_SEC_HAPTICS="VIBRAÇÃO"
ASB_SEC_BATTERY="BATERIA"
ASB_SEC_MEMORY="MEMÓRIA"
ASB_L_NOTICE_FOOT1="Tudo acima é ajustável na WebUI, e reiniciar"
ASB_L_NOTICE_FOOT2="aplica as partes que precisam."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="AutoSystemBoost instalado"
ASB_DONE_MSG="Reinicie o telefone para aplicar as alterações."
ASB_D_IDENTIFIED="identificado"
ASB_D_SOC="Processador"
ASB_D_MANAGER="gerenciador root"
ASB_D_FULL_PKG="pacote device-native completo para OnePlus 15"
ASB_D_STOCK_ANALYSIS="análise dos arquivos stock:"
ASB_D_FRESH="instalação limpa — padrões de fábrica"
ASB_D_MIGRATED="configurações de áudio migradas"
ASB_D_LEARN_RESET="aprendizado redefinido; configurações e dados do aparelho preservados"
ASB_D_GOV="daemon governor nativo em C"
ASB_D_DSP_ENGINE="motor DSP"
ASB_D_DSP_GAIN="ganho"
ASB_D_DSP_CHAIN="compressor soft-knee -> makeup gain -> limitador de pico (sem clipping)"
ASB_D_DSP_STAGED="biblioteca pronta para"
ASB_D_DSP_OFF="biblioteca pronta, efeito desligado"
ASB_D_DSP_REG="efeito registrado em"
ASB_D_DSP_REG_TAIL="arquivo(s) audio_effects_config"
ASB_D_LOUD="volume de mídia"
ASB_D_LOUD_AT="em volume médio"
ASB_D_LOUD_NOTE="só curvas de música; alarmes e toques intactos; 100% nunca é elevado"
ASB_D_MIXER="mixer"
ASB_D_MIXER_TAIL="arquivo(s) ajustados — volume digital 84->88"
ASB_D_MIXER_AGGR="DAC Class-H, modo HPH HIFI, compander desligado (agressivo)"
ASB_D_MIXER_STD="EQ plano, DAC Class-H"
ASB_D_OVERLAY="overlay alterado no local (EQ / volume / hi-res / codecs)"
ASB_D_CAM_TONE="tom da câmera: clonado device-stock"
ASB_D_CAM_AGGR_INJ="tom agressivo da câmera aplicado (incl. chaves adicionadas)"
ASB_D_CAM_AGGR_EXIST="tom agressivo da câmera aplicado (só chaves existentes)"
ASB_D_CAM_STOCK="câmera mantida stock (motor de ajustes ignorado)"
ASB_D_RETOUCH="apps de retoque"
ASB_D_MEDIA_LIFT="bitrate de vídeo elevado em"
ASB_D_MEDIA_TAIL="arquivo(s) device-native"
ASB_D_PERF="configs perf ajustadas"
ASB_D_PERF_TAIL="tempos de boost, game config"
ASB_D_FILES="arquivo(s)"
ASB_I_AFX_LIBS="bibliotecas de volume originais presentes (device-native)"
ASB_D_GPS="GPS/A-GPS ajustado"
ASB_D_WIFI_OK="config Wi-Fi WCNSS alterada (device-native)"
ASB_D_WIFI_NONE="nenhuma config WCNSS encontrada — Wi-Fi mantido stock"
ASB_D_BT="volume absoluto BT: desativado (o telefone controla o ganho)"
ASB_D_BT_NOTE="(o fone mantém o próprio nível; use 'stock' se o BT ficar baixo)"
ASB_D_BLUR="desfoque desativado via system.prop (após reiniciar)"
ASB_D_BOUNDS="limites device-adaptive: LIGADOS (OP15 — iguais ao ajuste de fábrica)"
ASB_L_MIRROR_AUDIO="copiados %s arquivo(s) de configuração de áudio — o ASB edita as cópias, nunca o sistema"
ASB_L_MIRROR_CAMERA="copiados %s arquivo(s) de configuração da câmera — o ASB edita as cópias, nunca o sistema"
ASB_L_MIRROR_SYSTEM="copiados %s arquivo(s) de configuração do sistema — o ASB edita as cópias, nunca o sistema"
ASB_L_CAM_TUNING="Câmera: ajuste de imagem pronto (cor, detalhe, nitidez)"
ASB_L_CAM_BEAUTY="Câmera: perfil de retoque pronto (ajustes por app)"
ASB_L_CAM_OTHER="Câmera: %s pronto"
ASB_L_CAM_PREPARED="Câmera: %s preparado a partir da cópia stock"
ASB_L_CAM_GRADED="Gradação da câmera: nível %s aplicado a %s arquivo(s) — saturação, detalhe por IA, nitidez"
ASB_L_TW_HIFI="Áudio: cadeia hi-fi — compressão do fabricante desligada, EQ plano"
ASB_L_TW_EQC="Áudio: ajustado para equalizadores externos (ViPER e similares)"
ASB_L_TW_LOUD="Volume: o nível confortável chega mais cedo no controle"
ASB_L_TW_DSP="DSP: ganho real de +%s dB, com limitador de pico"
ASB_L_TW_CAM="Câmera: nível de gradação %s — cor, detalhe por IA e nitidez elevados"
ASB_L_TW_PORTRAIT="Câmera: IA de retrato ligada (de fábrica desligada) — mais detalhe nos rostos"
ASB_L_TW_VIB_OFF="Vibração: desligada"
ASB_L_TW_VIB="Vibração: nível %s/10 na escala do fabricante"
ASB_L_TW_BLUR="Tela: desfoque desligado — menos carga na GPU, fundos sólidos"
ASB_L_TW_AUTOBAT="Bateria: muda para o perfil Bateria quando está baixa e volta após carregar"
ASB_L_TW_COOL="Jogos: a contenção térmica começa antes, o telefone fica mais fresco"
ASB_L_DSP_REG_N="registrado em %s arquivo(s) de configuração de áudio"
ASB_L_DSP_ODM="registrado na configuração que o Android realmente lê"
ASB_L_CAM_QUEUED="Câmera: %s configuração(ões) serão vinculadas na inicialização"
ASB_L_MMFEED_READY="Telemetria multimídia: patch pronto — desligado por padrão, ative na WebUI (Sistema)"
ASB_L_CALLREC_READY="Gravação de chamadas: patch pronto (%s arquivo(s)) — desligado por padrão, ative na WebUI (Sistema)"
ASB_L_VIB_SET="intensidade %s/10 na escala do fabricante, aplicada na hora"
ASB_L_VIB_TOUCH="resposta ao toque %s/10, definida à parte"
ASB_L_BAT_AUTO="muda para Bateria quando está baixa e volta após carregar"
ASB_L_BAT_CHARGE="mais folga ao carregar frio, menos quando aquece"
ASB_L_BAT_COOL="nos jogos a contenção térmica começa antes, telefone mais fresco"
ASB_L_MEM_TRIM="limpeza em segundo plano: %s"
ASB_L_CAM_BASE_FIX1="a referência da câmera de uma versão anterior já estava processada — descartada"
ASB_L_CAM_BASE_FIX2="ela será capturada de novo da cópia stock após este reinício"
ASB_L_CAM_LIVE_DIRTY1="a cor da câmera no aparelho foi processada por uma versão anterior — ignorando"
ASB_L_CAM_LIVE_DIRTY2="esta instalação ignora a cor da câmera; após reiniciar, basta instalar o ASB mais uma vez (não é preciso desativá-lo) — a referência é então tirada do ficheiro original"
ASB_L_FIX_SYSSYS="removido um caminho incorreto system/system de uma versão anterior"
ASB_I_OEM_KEPT="interruptores OEM atuais salvos"
ASB_I_PROFILE_KEPT="perfil de energia mantido"
ASB_I_PACK_CERT="pacote do aparelho certificado para este firmware"
ASB_I_DSP_ABI="efeito escolhido para este aparelho"
ASB_I_DSP_ATTACH="attacher pronto (cria o efeito na mixagem global)"
ASB_I_CAM_TUNING="ajuste da câmera: nível %s, aplicado a %s arquivo(s)"
ASB_I_RETOUCH_OK="pacote final da câmera verificado"
ASB_I_HP_LIMIT="limitador de volume dos fones removido — proteja sua audição"
ASB_INSTALL_WEBUI_FIRST="Todos os componentes prontos; os ajustes opcionais ficam em stock."
ASB_INSTALL_WEBUI_HINT="Após reiniciar, abra a WebUI e ative só o que quiser."
ASB_SUM_PROFILE="perfil"
ASB_SUM_NOTES="Vale a pena ler"
ASB_SUM_WEBUI="Configurações: a WebUI do módulo, após reiniciar"
