#!/system/bin/sh

ASB_HINT="[VOL+] Включить | [VOL-] Пропустить"
ASB_TIMEOUT="! Время вышло (10 секунд). Установка отменена."

ASB_HELP="VOL+ = включить  |  VOL- = пропустить  |  таймаут 10с = отмена"

ASB_CFG_FOUND_TITLE="Найдена сохранённая конфигурация"
ASB_CFG_FOUND_HINT="VOL+ = использовать сохранённую  |  VOL- = выбрать заново"
ASB_CFG_USING_SAVED="Использую сохранённую конфигурацию от:"
ASB_CFG_RESELECT="Выбираю категории заново..."
ASB_CFG_SAVED_TO="Конфигурация сохранена:"

ASB_MENU_AUDIO=" 1) АУДИО (HAL/Кодеки/Эффекты/Микшеры)"
ASB_MENU_BT="2) Bluetooth (A2DP/LE Audio/Кодеки)"
ASB_MENU_CAMERA="3) КАМЕРА (Фото/Видео)"
ASB_MENU_CPU="4) CPU (Планировщик/Частоты)"
ASB_MENU_VM="5) VM (Память/Dirty/Swappiness)"
ASB_MENU_NET="6) NET (TCP/QDISC/Буферы/Очереди)"
ASB_MENU_WIFI="7) WiFi (Скан/Сон)"
ASB_MENU_GPS="8) GPS (GNSS)"
ASB_MENU_KERNEL="9) ЯДРО (Printk/Perf)"
ASB_MENU_LOG="10) ЛОГИ (Сервисы/Шум)"
ASB_MENU_RADIO_IMS="11) РАДИО/IMS (VoLTE/VoNR/IMS авторизация)"
ASB_MENU_DISPLAY="12) ДИСПЛЕЙ (CABL/DPPS/Подсветка)"
ASB_MENU_FPS="13) FPS (Частота кадров/Запись)"
ASB_MENU_SECURITY="14) БЕЗОПАСНОСТЬ (Perf события/Снапшоты)"
ASB_MENU_BG_TRIM="15) BG_TRIM (Телеметрия + Wakeup'ы + Doze)"

ASB_DONE_TITLE="ASB"
ASB_DONE_MSG="Модуль установлен! Перезагрузка обязательна."

# --- install progress section headers (V61) ---
ASB_SEC_DEVICE="УСТРОЙСТВО"
ASB_SEC_CONFIG="КОНФИГУРАЦИЯ"
ASB_SEC_GOVERNOR="ГУБЕРНАТОР"
ASB_SEC_AUDIO="АУДИО"
ASB_SEC_CAMERA="КАМЕРА"
ASB_SEC_MEDIA="МЕДИА"
ASB_SEC_PERF="ПРОИЗВОДИТЕЛЬНОСТЬ"
ASB_SEC_LOCATION="ГЕОЛОКАЦИЯ"
ASB_SEC_WIFI="WI-FI"
ASB_SEC_SYSTEM="СИСТЕМА"
ASB_SEC_CATEGORIES="ПОДГОТОВЛЕННЫЕ КОМПОНЕНТЫ"
ASB_SEC_INSTALLING="установка для"
ASB_SEC_BUILDING="сборка device-native оверлея из стоковых файлов этого устройства"

# --- install progress detail lines (V61) ---
ASB_D_IDENTIFIED="определено"
ASB_D_SOC="Процессор"
ASB_D_MANAGER="рут-менеджер"
ASB_D_FULL_PKG="полный device-native пакет для OnePlus 15"
ASB_D_STOCK_ANALYSIS="анализ стоковых файлов:"
ASB_D_FRESH="чистая установка — настройки по умолчанию"
ASB_D_MIGRATED="настройки звука перенесены"
ASB_D_LEARN_RESET="обучение сброшено; настройки и данные устройства сохранены"
ASB_D_GOV="нативный C-демон губернатора"
ASB_D_DSP_ENGINE="движок DSP"
ASB_D_DSP_GAIN="усиление"
ASB_D_DSP_CHAIN="мягкое колено -> makeup gain -> пиковый лимитер (без клиппинга)"
ASB_D_DSP_STAGED="библиотека для"
ASB_D_DSP_OFF="библиотека установлена, эффект выкл"
ASB_D_DSP_REG="эффект зарегистрирован в"
ASB_D_DSP_REG_TAIL="файле(ах) audio_effects_config"
ASB_D_LOUD="громкость медиа"
ASB_D_LOUD_AT="на средней громкости"
ASB_D_LOUD_NOTE="только музыкальные кривые; будильники/рингтоны не тронуты; 100% не поднимается"
ASB_D_MIXER="микшер"
ASB_D_MIXER_TAIL="файл(ов) настроено — цифр. громкость 84->88"
ASB_D_MIXER_AGGR="Class-H ЦАП, режим HPH HIFI, компандер выкл (агрессивный)"
ASB_D_MIXER_STD="плоский EQ, Class-H ЦАП"
ASB_D_OVERLAY="оверлей пропатчен на месте (EQ / громкость / hi-res / кодеки)"
ASB_D_CAM_TONE="тон камеры: клонирован device-stock"
ASB_D_CAM_AGGR_INJ="агрессивный тон камеры применён (вкл. добавленные ключи)"
ASB_D_CAM_AGGR_EXIST="агрессивный тон камеры применён (только существующие ключи)"
ASB_D_CAM_STOCK="камера оставлена стокй (движок твиков пропущен)"
ASB_D_RETOUCH="приложения ретуши"
ASB_D_MEDIA_LIFT="битрейт видео поднят в"
ASB_D_MEDIA_TAIL="device-native файле(ах)"
ASB_D_PERF="perf-конфиги настроены"
ASB_D_PERF_TAIL="таймауты буста, game config"
ASB_D_GPS="GPS/A-GPS настроен"
ASB_D_WIFI_OK="конфиг WCNSS Wi-Fi пропатчен (device-native)"
ASB_D_WIFI_NONE="конфиг WCNSS не найден — Wi-Fi оставлен стоковым"
ASB_D_BT="абсолютная громкость BT: отключена (усилением управляет телефон)"
ASB_D_BT_NOTE="(гарнитура держит свой уровень; используйте 'stock' если BT тихий)"
ASB_D_BLUR="блюр отключён через system.prop (применится после перезагрузки)"
ASB_D_BOUNDS="device-adaptive границы: ВКЛ (OP15 — совпадают с заводской настройкой)"

# ── V61: понятный вывод установщика ───────────────────────────────────────────
ASB_L_MIRROR_AUDIO="скопировано аудио-настроек: %s — ASB правит копии, а не систему"
ASB_L_MIRROR_AUDIO_TOTAL="скопировано аудио-настроек: %s из %s device-native путей — ASB правит копии, а не систему"
ASB_L_MIRROR_CAMERA="скопировано настроек камеры: %s — ASB правит копии, а не систему"
ASB_L_MIRROR_SYSTEM="скопировано системных настроек: %s — ASB правит копии, а не систему"
ASB_L_CAM_TUNING="Камера: настройка изображения готова (цвет, детализация, резкость)"
ASB_L_CAM_BEAUTY="Камера: профиль ретуши готов (настройки по приложениям)"
ASB_L_CAM_OTHER="Камера: %s готов"
ASB_L_CAM_PREPARED="Камера: %s подготовлен из стокй копии"
ASB_L_CAM_GRADED="Обработка камеры: уровень %s применён к файлам: %s — насыщенность, ИИ-детализация, резкость"
ASB_SEC_NOTICE="ЧТО ВЫ ЗАМЕТИТЕ"
ASB_L_TW_HIFI="Звук: тракт hi-fi — вендорное сжатие выключено, ровный эквалайзер"
ASB_L_TW_EQC="Звук: настроено под внешние эквалайзеры (ViPER и подобные)"
ASB_L_TW_LOUD="Громкость: комфортный уровень достигается ниже по шкале"
ASB_L_TW_DSP="DSP: реальное усиление +%s дБ, с пиковым лимитером"
ASB_L_TW_CAM="Камера: уровень обработки %s — цвет, ИИ-детализация и резкость подняты"
ASB_L_TW_PORTRAIT="Камера: ИИ для портретов включён (в стоке выключен) — больше деталей на лицах"
ASB_L_TW_VIB_OFF="Вибрация: выключена"
ASB_L_TW_VIB="Вибрация: уровень %s/10 по фирменной шкале"
ASB_L_TW_BLUR="Экран: размытие выключено — меньше нагрузки на GPU, непрозрачные подложки"
ASB_L_TW_AUTOBAT="Батарея: при низком заряде переключается на профиль Экономия и обратно после зарядки"
ASB_L_TW_COOL="Игры: термо-уклон включается раньше, телефон холоднее"
ASB_L_NOTICE_FOOT1="Всё перечисленное настраивается в WebUI, а перезагрузка"
ASB_L_NOTICE_FOOT2="применяет то, что её требует."

ASB_SEC_DSP="DSP-ДВИЖОК"
ASB_SEC_DISPLAY="ЭКРАН"
ASB_SEC_HAPTICS="ВИБРАЦИЯ"
ASB_SEC_BATTERY="БАТАРЕЯ"
ASB_SEC_MEMORY="ПАМЯТЬ"
ASB_L_DSP_REG_N="зарегистрирован в аудио-конфигах: %s"
ASB_L_DSP_ODM="зарегистрирован в том конфиге, который Android действительно читает"
ASB_L_CAM_QUEUED="Камера: конфигов будет подключено при загрузке: %s"
ASB_L_VIB_SET="сила %s/10 по фирменной шкале, применено сразу"
ASB_L_VIB_TOUCH="отклик касаний %s/10, задан отдельно"
ASB_L_BAT_AUTO="при низком заряде переключается на Экономию и обратно после зарядки"
ASB_L_BAT_CHARGE="больше запаса на холодной зарядке, меньше при нагреве"
ASB_L_BAT_COOL="в играх термо-уклон включается раньше, телефон холоднее"
ASB_L_MEM_TRIM="очистка фона: %s"
ASB_L_CAM_BASE_FIX1="эталон камеры от старой сборки уже был обработан — удалён"
ASB_L_CAM_BASE_FIX2="он будет снят заново со стокй копии после этой перезагрузки"
ASB_L_CAM_LIVE_DIRTY1="цвет камеры на устройстве обработан прошлой сборкой — пропускаем его"
ASB_L_CAM_LIVE_DIRTY2="перезагрузитесь и установите ещё раз — эталон снимется сам, повторной обработки не будет"
ASB_L_FIX_SYSSYS="удалён ошибочный путь system/system от прошлой сборки"
