#!/system/bin/sh

# Spanish installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank. The strings
# chosen are the ones a user actually reads during an install - prompts, section
# headings and the closing note. Per-tweak detail lines remain English until someone
# who speaks the language writes them; a machine-translated technical claim that reads
# fluently and says the wrong thing is worse than English.

ASB_HINT="[VOL+] Activar | [VOL-] Omitir"
ASB_TIMEOUT="! Tiempo agotado (10 segundos). Instalación cancelada."
ASB_HELP="VOL+ = activar  |  VOL- = omitir  |  10s sin pulsar = cancelar"
ASB_SEC_DEVICE="DISPOSITIVO"
ASB_SEC_CONFIG="CONFIGURACIÓN"
ASB_SEC_GOVERNOR="GOBERNADOR"
ASB_SEC_AUDIO="AUDIO"
ASB_SEC_BT="BLUETOOTH"
ASB_SEC_CAMERA="CÁMARA"
ASB_SEC_MEDIA="MULTIMEDIA"
ASB_SEC_PERF="RENDIMIENTO"
ASB_SEC_LOCATION="UBICACIÓN"
ASB_SEC_WIFI="WIFI"
ASB_SEC_SYSTEM="SISTEMA"
ASB_SEC_CATEGORIES="COMPONENTES PREPARADOS"
ASB_L_MIRROR_AUDIO_TOTAL="copiados %s archivo(s) de configuración de audio de %s carpeta(s) device-native — ASB edita las copias, nunca el sistema"
ASB_SEC_INSTALLING="instalando para"
ASB_SEC_BUILDING="creando una capa a partir de los archivos originales de este teléfono"
ASB_SEC_NOTICE="LO QUE NOTARÁS"
ASB_SEC_DSP="MOTOR DSP"
ASB_SEC_DISPLAY="PANTALLA"
ASB_SEC_HAPTICS="VIBRACIÓN"
ASB_SEC_BATTERY="BATERÍA"
ASB_SEC_MEMORY="MEMORIA"
ASB_L_NOTICE_FOOT1="Todo lo anterior se ajusta en la WebUI, y un reinicio"
ASB_L_NOTICE_FOOT2="aplica las partes que lo necesitan."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="AutoSystemBoost instalado"
ASB_DONE_MSG="Reinicia el teléfono para aplicar los cambios."
ASB_D_IDENTIFIED="detectado"
ASB_D_SOC="Procesador"
ASB_D_MANAGER="gestor root"
ASB_D_FULL_PKG="paquete device-native completo para OnePlus 15"
ASB_D_STOCK_ANALYSIS="análisis de archivos stock:"
ASB_D_FRESH="instalación limpia — valores predeterminados"
ASB_D_MIGRATED="ajustes de audio migrados"
ASB_D_LEARN_RESET="aprendizaje reiniciado; ajustes y datos del dispositivo conservados"
ASB_D_GOV="demonio governor nativo en C"
ASB_D_DSP_ENGINE="motor DSP"
ASB_D_DSP_GAIN="ganancia"
ASB_D_DSP_CHAIN="compresor soft-knee -> makeup gain -> limitador de picos (sin clipping)"
ASB_D_DSP_STAGED="biblioteca lista para"
ASB_D_DSP_OFF="biblioteca lista, efecto apagado"
ASB_D_DSP_REG="efecto registrado en"
ASB_D_DSP_REG_TAIL="archivo(s) audio_effects_config"
ASB_D_LOUD="volumen multimedia"
ASB_D_LOUD_AT="a volumen medio"
ASB_D_LOUD_NOTE="solo curvas de música; alarmas y tonos intactos; el 100% nunca se sube"
ASB_D_MIXER="mezclador"
ASB_D_MIXER_TAIL="archivo(s) ajustados — volumen digital 84->88"
ASB_D_MIXER_AGGR="DAC Class-H, modo HPH HIFI, compander apagado (agresivo)"
ASB_D_MIXER_STD="EQ plano, DAC Class-H"
ASB_D_OVERLAY="overlay parcheado in situ (EQ / volumen / hi-res / códecs)"
ASB_D_CAM_TONE="tono de cámara: clonado device-stock"
ASB_D_CAM_AGGR_INJ="tono de cámara agresivo aplicado (incl. claves añadidas)"
ASB_D_CAM_AGGR_EXIST="tono de cámara agresivo aplicado (solo claves existentes)"
ASB_D_CAM_STOCK="cámara en stock (motor de ajustes omitido)"
ASB_D_RETOUCH="apps de retoque"
ASB_D_MEDIA_LIFT="bitrate de vídeo aumentado en"
ASB_D_MEDIA_TAIL="archivo(s) device-native"
ASB_D_PERF="configs perf ajustadas"
ASB_D_PERF_TAIL="tiempos de boost, game config"
ASB_D_FILES="archivo(s)"
ASB_I_AFX_LIBS="bibliotecas de volumen originales presentes (device-native)"
ASB_D_GPS="GPS/A-GPS ajustado"
ASB_D_WIFI_OK="config Wi-Fi WCNSS parcheada (device-native)"
ASB_D_WIFI_NONE="no se encontró config WCNSS — Wi-Fi en stock"
ASB_D_BT="volumen absoluto BT: desactivado (el teléfono controla la ganancia)"
ASB_D_BT_NOTE="(los auriculares mantienen su nivel; usa 'stock' si el BT suena bajo)"
ASB_D_BLUR="desenfoque desactivado vía system.prop (tras reiniciar)"
ASB_D_BOUNDS="límites device-adaptive: ACTIVADOS (OP15 — coinciden con el ajuste de fábrica)"
ASB_L_MIRROR_AUDIO="copiados %s archivo(s) de ajustes de audio — ASB edita las copias, nunca el sistema"
ASB_L_MIRROR_CAMERA="copiados %s archivo(s) de ajustes de cámara — ASB edita las copias, nunca el sistema"
ASB_L_MIRROR_SYSTEM="copiados %s archivo(s) de ajustes del sistema — ASB edita las copias, nunca el sistema"
ASB_L_CAM_TUNING="Cámara: ajuste de imagen listo (color, detalle, nitidez)"
ASB_L_CAM_BEAUTY="Cámara: perfil de retoque listo (ajustes por app)"
ASB_L_CAM_OTHER="Cámara: %s listo"
ASB_L_CAM_PREPARED="Cámara: %s preparado desde la copia stock"
ASB_L_CAM_GRADED="Gradación de cámara: nivel %s aplicado a %s archivo(s) — saturación, detalle IA, nitidez"
ASB_L_TW_HIFI="Audio: cadena hi-fi — compresión del fabricante apagada, EQ plano"
ASB_L_TW_EQC="Audio: ajustado para ecualizadores externos (ViPER y similares)"
ASB_L_TW_LOUD="Volumen: el nivel cómodo se alcanza más abajo en el control"
ASB_L_TW_DSP="DSP: ganancia real de +%s dB, con limitador de picos"
ASB_L_TW_CAM="Cámara: nivel de gradación %s — color, detalle IA y nitidez aumentados"
ASB_L_TW_PORTRAIT="Cámara: IA de retrato activada (de serie apagada) — más detalle en los rostros"
ASB_L_TW_VIB_OFF="Vibración: apagada"
ASB_L_TW_VIB="Vibración: nivel %s/10 en la escala del fabricante"
ASB_L_TW_BLUR="Pantalla: desenfoque apagado — menos carga para la GPU, fondos sólidos"
ASB_L_TW_AUTOBAT="Batería: cambia al perfil Batería cuando queda poca y vuelve tras cargar"
ASB_L_TW_COOL="Juegos: la contención térmica empieza antes, el teléfono se mantiene más fresco"
ASB_L_DSP_REG_N="registrado en %s archivo(s) de configuración de audio"
ASB_L_DSP_ODM="registrado en la configuración que Android realmente lee"
ASB_L_CAM_QUEUED="Cámara: %s configuración(es) se enlazarán al arrancar"
ASB_L_MMFEED_READY="Telemetría multimedia: parche listo — apagado por defecto, se activa en la WebUI (Sistema)"
ASB_L_CALLREC_READY="Grabación de llamadas: parche listo (%s archivo(s)) — apagado por defecto, se activa en la WebUI (Sistema)"
ASB_L_VIB_SET="intensidad %s/10 en la escala del fabricante, aplicada al momento"
ASB_L_VIB_TOUCH="respuesta táctil %s/10, ajustada por separado"
ASB_L_BAT_AUTO="cambia a Batería cuando queda poca y vuelve tras cargar"
ASB_L_BAT_CHARGE="más margen al cargar en frío, menos cuando se calienta"
ASB_L_BAT_COOL="en juegos la contención térmica empieza antes, teléfono más fresco"
ASB_L_MEM_TRIM="limpieza en segundo plano: %s"
ASB_L_CAM_BASE_FIX1="la referencia de cámara de una versión anterior ya estaba procesada — descartada"
ASB_L_CAM_BASE_FIX2="se volverá a capturar desde la copia stock tras este reinicio"
ASB_L_CAM_LIVE_DIRTY1="el color de cámara del dispositivo fue procesado por una versión anterior — se omite"
ASB_L_CAM_LIVE_DIRTY2="esta instalación omite el color de cámara; tras reiniciar, basta con instalar ASB una vez más (no hace falta desactivarlo) — la referencia se toma del archivo original"
ASB_L_FIX_SYSSYS="eliminada una ruta errónea system/system de una versión anterior"
ASB_I_OEM_KEPT="guardados los interruptores OEM actuales"
ASB_I_PROFILE_KEPT="perfil de energía conservado"
ASB_I_PACK_CERT="paquete del dispositivo certificado para este firmware"
ASB_I_DSP_ABI="efecto elegido para este dispositivo"
ASB_I_DSP_ATTACH="attacher listo (crea el efecto en la mezcla global)"
ASB_I_CAM_TUNING="ajuste de cámara: nivel %s, aplicado a %s archivo(s)"
ASB_I_RETOUCH_OK="paquete final de cámara verificado"
ASB_I_HP_LIMIT="limitador de volumen de auriculares eliminado — cuida tu audición"
ASB_INSTALL_WEBUI_FIRST="Todos los componentes listos; los ajustes opcionales siguen en stock."
ASB_INSTALL_WEBUI_HINT="Tras reiniciar, abre la WebUI y activa solo lo que quieras."
ASB_SUM_PROFILE="perfil"
ASB_SUM_NOTES="Conviene leer"
ASB_SUM_WEBUI="Ajustes: la WebUI del módulo, tras reiniciar"
