#!/system/bin/sh

# Turkish installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank. The strings
# chosen are the ones a user actually reads during an install - prompts, section
# headings and the closing note. Per-tweak detail lines remain English until someone
# who speaks the language writes them; a machine-translated technical claim that reads
# fluently and says the wrong thing is worse than English.

ASB_HINT="[VOL+] Etkinleştir | [VOL-] Atla"
ASB_TIMEOUT="! Süre doldu (10 saniye). Kurulum iptal edildi."
ASB_HELP="VOL+ = etkinleştir  |  VOL- = atla  |  10sn zaman aşımı = iptal"
ASB_SEC_DEVICE="CİHAZ"
ASB_SEC_CONFIG="YAPILANDIRMA"
ASB_SEC_GOVERNOR="GOVERNOR"
ASB_SEC_AUDIO="SES"
ASB_SEC_BT="BLUETOOTH"
ASB_SEC_CAMERA="KAMERA"
ASB_SEC_MEDIA="MEDYA"
ASB_SEC_PERF="PERFORMANS"
ASB_SEC_LOCATION="KONUM"
ASB_SEC_WIFI="WI-FI"
ASB_SEC_SYSTEM="SİSTEM"
ASB_SEC_CATEGORIES="HAZIRLANAN BİLEŞENLER"
ASB_L_MIRROR_AUDIO_TOTAL="%s ses yapılandırma dosyası %s device-native klasörden kopyalandı — ASB kopyaları düzenler, sistemi asla"
ASB_SEC_INSTALLING="şunun için kuruluyor"
ASB_SEC_BUILDING="bu telefonun kendi orijinal dosyalarından katman oluşturuluyor"
ASB_SEC_NOTICE="NE FARK EDECEKSİNİZ"
ASB_SEC_DSP="DSP MOTORU"
ASB_SEC_DISPLAY="EKRAN"
ASB_SEC_HAPTICS="TİTREŞİM"
ASB_SEC_BATTERY="PİL"
ASB_SEC_MEMORY="BELLEK"
ASB_L_NOTICE_FOOT1="Yukarıdakilerin tümü WebUI\u2019dan ayarlanabilir; yeniden başlatma"
ASB_L_NOTICE_FOOT2="gerektiren kısımları uygular."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="AutoSystemBoost kuruldu"
ASB_DONE_MSG="Değişikliklerin uygulanması için telefonu yeniden başlatın."
ASB_D_IDENTIFIED="algılandı"
ASB_D_SOC="İşlemci"
ASB_D_MANAGER="root yöneticisi"
ASB_D_FULL_PKG="OnePlus 15 için tam device-native paket"
ASB_D_STOCK_ANALYSIS="stok dosya analizi:"
ASB_D_FRESH="temiz kurulum — varsayılan ayarlar"
ASB_D_MIGRATED="ses ayarları taşındı"
ASB_D_LEARN_RESET="öğrenme sıfırlandı; ayarlar ve cihaz verileri korundu"
ASB_D_GOV="yerel C governor servisi"
ASB_D_DSP_ENGINE="DSP motoru"
ASB_D_DSP_GAIN="kazanç"
ASB_D_DSP_CHAIN="yumuşak dizli kompresör -> makeup gain -> tepe sınırlayıcı (kırpma yok)"
ASB_D_DSP_STAGED="kitaplık hazır:"
ASB_D_DSP_OFF="kitaplık hazır, efekt kapalı"
ASB_D_DSP_REG="efekt kaydedildi:"
ASB_D_DSP_REG_TAIL="audio_effects_config dosyası"
ASB_D_LOUD="medya ses düzeyi"
ASB_D_LOUD_AT="orta seste"
ASB_D_LOUD_NOTE="yalnızca müzik eğrileri; alarm ve zil sesleri dokunulmadı; %100 asla yükseltilmez"
ASB_D_MIXER="mikser"
ASB_D_MIXER_TAIL="dosya ayarlandı — dijital ses 84->88"
ASB_D_MIXER_AGGR="Class-H DAC, HPH HIFI modu, kompander kapalı (agresif)"
ASB_D_MIXER_STD="düz EQ, Class-H DAC"
ASB_D_OVERLAY="overlay yerinde yamalandı (EQ / ses / hi-res / kodekler)"
ASB_D_CAM_TONE="kamera tonu: device-stock kopyalandı"
ASB_D_CAM_AGGR_INJ="agresif kamera tonu uygulandı (eklenen anahtarlar dahil)"
ASB_D_CAM_AGGR_EXIST="agresif kamera tonu uygulandı (yalnızca mevcut anahtarlar)"
ASB_D_CAM_STOCK="kamera stok bırakıldı (ayar motoru atlandı)"
ASB_D_RETOUCH="rötuş uygulamaları"
ASB_D_MEDIA_LIFT="video bit hızı yükseltildi:"
ASB_D_MEDIA_TAIL="device-native dosya"
ASB_D_PERF="perf yapılandırmaları ayarlandı"
ASB_D_PERF_TAIL="boost zaman aşımları, game config"
ASB_D_FILES="dosya"
ASB_I_AFX_LIBS="stok ses kitaplıkları mevcut (device-native)"
ASB_D_GPS="GPS/A-GPS ayarlandı"
ASB_D_WIFI_OK="WCNSS Wi-Fi yapılandırması yamalandı (device-native)"
ASB_D_WIFI_NONE="WCNSS yapılandırması bulunamadı — Wi-Fi stok bırakıldı"
ASB_D_BT="BT mutlak ses: kapalı (kazancı telefon yönetir)"
ASB_D_BT_NOTE="(kulaklık kendi seviyesini korur; BT kısık gelirse 'stock' seçin)"
ASB_D_BLUR="bulanıklık system.prop ile kapatıldı (yeniden başlatmadan sonra)"
ASB_D_BOUNDS="device-adaptive sınırlar: AÇIK (OP15 — fabrika ayarıyla aynı)"
ASB_L_MIRROR_AUDIO="%s ses ayarı dosyası kopyalandı — ASB kopyaları düzenler, sistemi asla"
ASB_L_MIRROR_CAMERA="%s kamera ayarı dosyası kopyalandı — ASB kopyaları düzenler, sistemi asla"
ASB_L_MIRROR_SYSTEM="%s sistem ayarı dosyası kopyalandı — ASB kopyaları düzenler, sistemi asla"
ASB_L_CAM_TUNING="Kamera: görüntü ayarı hazır (renk, ayrıntı, keskinlik)"
ASB_L_CAM_BEAUTY="Kamera: rötuş profili hazır (uygulama başına ayarlar)"
ASB_L_CAM_OTHER="Kamera: %s hazır"
ASB_L_CAM_PREPARED="Kamera: %s stok kopyadan hazırlandı"
ASB_L_CAM_GRADED="Kamera işleme: seviye %s, %s dosyaya uygulandı — doygunluk, YZ ayrıntısı, keskinlik"
ASB_L_TW_HIFI="Ses: hi-fi zinciri — üretici sıkıştırması kapalı, düz EQ"
ASB_L_TW_EQC="Ses: harici ekolayzırlar için ayarlandı (ViPER ve benzerleri)"
ASB_L_TW_LOUD="Ses düzeyi: rahat seviyeye kaydırıcının daha altında ulaşılır"
ASB_L_TW_DSP="DSP: gerçek +%s dB kazanç, tepe sınırlayıcıyla"
ASB_L_TW_CAM="Kamera: işleme seviyesi %s — renk, YZ ayrıntısı ve keskinlik artırıldı"
ASB_L_TW_PORTRAIT="Kamera: portre YZ açık (fabrikada kapalı) — yüzlerde daha fazla ayrıntı"
ASB_L_TW_VIB_OFF="Titreşim: kapalı"
ASB_L_TW_VIB="Titreşim: üretici ölçeğinde %s/10 seviye"
ASB_L_TW_BLUR="Ekran: bulanıklık kapalı — GPU'ya daha az yük, düz arka planlar"
ASB_L_TW_AUTOBAT="Pil: azaldığında Pil profiline geçer, şarjdan sonra geri döner"
ASB_L_TW_COOL="Oyunlar: ısı kısıtlaması daha erken başlar, telefon daha serin kalır"
ASB_L_DSP_REG_N="%s ses yapılandırma dosyasına kaydedildi"
ASB_L_DSP_ODM="Android'in gerçekten okuduğu yapılandırmaya kaydedildi"
ASB_L_CAM_QUEUED="Kamera: %s yapılandırma açılışta bağlanacak"
ASB_L_MMFEED_READY="Multimedya telemetrisi: yama hazır — varsayılan olarak kapalı, WebUI'den (Sistem) açılır"
ASB_L_CALLREC_READY="Arama kaydı: yama hazır (%s dosya) — varsayılan olarak kapalı, WebUI'den (Sistem) açılır"
ASB_L_VIB_SET="güç %s/10 üretici ölçeğinde, hemen uygulandı"
ASB_L_VIB_TOUCH="dokunma geri bildirimi %s/10, ayrıca ayarlandı"
ASB_L_BAT_AUTO="azaldığında Pil profiline geçer, şarjdan sonra geri döner"
ASB_L_BAT_CHARGE="serinken şarjda daha fazla pay, ısındıkça daha az"
ASB_L_BAT_COOL="oyunlarda ısı kısıtlaması daha erken başlar, telefon daha serin"
ASB_L_MEM_TRIM="arka plan temizliği: %s"
ASB_L_CAM_BASE_FIX1="eski sürümden kalan kamera referansı zaten işlenmişti — silindi"
ASB_L_CAM_BASE_FIX2="bu yeniden başlatmadan sonra stok kopyadan yeniden alınacak"
ASB_L_CAM_LIVE_DIRTY1="cihazdaki kamera rengi önceki bir sürümle işlenmiş — atlanıyor"
ASB_L_CAM_LIVE_DIRTY2="bu kurulum kamera rengini atlar; yeniden başlattıktan sonra ASB'yi bir kez daha kurmanız yeterli (devre dışı bırakmaya gerek yok) — referans orijinal dosyadan alınır"
ASB_L_FIX_SYSSYS="önceki sürümden kalan hatalı system/system yolu kaldırıldı"
ASB_I_OEM_KEPT="mevcut OEM anahtarları kaydedildi"
ASB_I_PROFILE_KEPT="güç profili korundu"
ASB_I_PACK_CERT="cihaz paketi bu yazılım için onaylandı"
ASB_I_DSP_ABI="bu cihaz için efekt seçildi"
ASB_I_DSP_ATTACH="attacher hazır (efekti genel mikste oluşturur)"
ASB_I_CAM_TUNING="kamera ayarı: seviye %s, %s dosyaya uygulandı"
ASB_I_RETOUCH_OK="son kamera paketi doğrulandı"
ASB_I_HP_LIMIT="kulaklık ses sınırlayıcısı kaldırıldı — işitmenizi koruyun"
ASB_INSTALL_WEBUI_FIRST="Tüm bileşenler hazır; isteğe bağlı ayarlar stok kalır."
ASB_INSTALL_WEBUI_HINT="Yeniden başlattıktan sonra WebUI'yi açın ve yalnızca istediklerinizi etkinleştirin."
ASB_SUM_PROFILE="profil"
ASB_SUM_NOTES="Okumaya değer"
ASB_SUM_WEBUI="Ayarlar: modülün WebUI'si, yeniden başlatmadan sonra"
