#!/system/bin/sh

# Ukrainian installer strings.
#
# Partial by design: install.sh sources englishtext.sh first and then this file, so
# anything not translated here stays readable English rather than blank. The strings
# chosen are the ones a user actually reads during an install - prompts, section
# headings and the closing note. Per-tweak detail lines remain English until someone
# who speaks the language writes them; a machine-translated technical claim that reads
# fluently and says the wrong thing is worse than English.

ASB_HINT="[VOL+] Увімкнути | [VOL-] Пропустити"
ASB_TIMEOUT="! Час вийшов (10 секунд). Встановлення скасовано."
ASB_HELP="VOL+ = увімкнути  |  VOL- = пропустити  |  таймаут 10с = скасування"
ASB_SEC_DEVICE="ПРИСТРІЙ"
ASB_SEC_CONFIG="КОНФІГУРАЦІЯ"
ASB_SEC_GOVERNOR="ГУБЕРНАТОР"
ASB_SEC_AUDIO="АУДІО"
ASB_SEC_BT="BLUETOOTH"
ASB_SEC_CAMERA="КАМЕРА"
ASB_SEC_MEDIA="МЕДІА"
ASB_SEC_PERF="ПРОДУКТИВНІСТЬ"
ASB_SEC_LOCATION="ГЕОЛОКАЦІЯ"
ASB_SEC_WIFI="WI-FI"
ASB_SEC_SYSTEM="СИСТЕМА"
ASB_SEC_CATEGORIES="ПІДГОТОВЛЕНІ КОМПОНЕНТИ"
ASB_L_MIRROR_AUDIO_TOTAL="скопійовано файлів аудіо-налаштувань: %s з %s device-native тек — ASB редагує копії, а не систему"
ASB_SEC_INSTALLING="встановлення для"
ASB_SEC_BUILDING="створюємо накладку з рідних файлів саме цього телефона"
ASB_SEC_NOTICE="ЩО ВИ ПОМІТИТЕ"
ASB_SEC_DSP="DSP-ДВИГУН"
ASB_SEC_DISPLAY="ЕКРАН"
ASB_SEC_HAPTICS="ВІБРАЦІЯ"
ASB_SEC_BATTERY="БАТАРЕЯ"
ASB_SEC_MEMORY="ПАМʼЯТЬ"
ASB_L_NOTICE_FOOT1="Усе перелічене налаштовується у WebUI, а перезавантаження"
ASB_L_NOTICE_FOOT2="застосовує те, що його потребує."

# Full installer translation (detail lines, notices, summary)
ASB_DONE_TITLE="AutoSystemBoost встановлено"
ASB_DONE_MSG="Перезавантажте телефон, щоб усе запрацювало."
ASB_D_IDENTIFIED="визначено"
ASB_D_SOC="процесор"
ASB_D_MANAGER="рут-менеджер"
ASB_D_FULL_PKG="повний device-native пакет для OnePlus 15"
ASB_D_STOCK_ANALYSIS="аналіз стокових файлів:"
ASB_D_FRESH="чисте встановлення — налаштування за замовчуванням"
ASB_D_MIGRATED="налаштування звуку перенесено"
ASB_D_LEARN_RESET="навчання скинуто; налаштування й дані пристрою збережено"
ASB_D_GOV="нативний C-демон губернатора"
ASB_D_DSP_ENGINE="рушій DSP"
ASB_D_DSP_GAIN="підсилення"
ASB_D_DSP_CHAIN="м'яке коліно -> makeup gain -> піковий лімітер (без кліпінгу)"
ASB_D_DSP_STAGED="бібліотека для"
ASB_D_DSP_OFF="бібліотеку встановлено, ефект вимкнено"
ASB_D_DSP_REG="ефект зареєстровано в"
ASB_D_DSP_REG_TAIL="файлі(ах) audio_effects_config"
ASB_D_LOUD="гучність медіа"
ASB_D_LOUD_AT="на середній гучності"
ASB_D_LOUD_NOTE="лише музичні криві; будильники й рингтони не зачеплено; 100% не піднімається"
ASB_D_MIXER="мікшер"
ASB_D_MIXER_TAIL="файл(ів) налаштовано — цифр. гучність 84->88"
ASB_D_MIXER_AGGR="Class-H ЦАП, режим HPH HIFI, компандер вимк. (агресивний)"
ASB_D_MIXER_STD="рівний EQ, Class-H ЦАП"
ASB_D_OVERLAY="оверлей пропатчено на місці (EQ / гучність / hi-res / кодеки)"
ASB_D_CAM_TONE="тон камери: клоновано device-stock"
ASB_D_CAM_AGGR_INJ="агресивний тон камери застосовано (вкл. додані ключі)"
ASB_D_CAM_AGGR_EXIST="агресивний тон камери застосовано (лише наявні ключі)"
ASB_D_CAM_STOCK="камеру залишено стоковою (рушій твіків пропущено)"
ASB_D_RETOUCH="застосунки ретуші"
ASB_D_MEDIA_LIFT="бітрейт відео піднято в"
ASB_D_MEDIA_TAIL="device-native файлі(ах)"
ASB_D_PERF="perf-конфіги налаштовано"
ASB_D_PERF_TAIL="тайм-аути бусту, game config"
ASB_D_FILES="файл(ів)"
ASB_I_AFX_LIBS="стокові бібліотеки гучності на місці (device-native)"
ASB_D_GPS="GPS/A-GPS налаштовано"
ASB_D_WIFI_OK="конфіг WCNSS Wi-Fi пропатчено (device-native)"
ASB_D_WIFI_NONE="конфіг WCNSS не знайдено — Wi-Fi залишено стоковим"
ASB_D_BT="абсолютна гучність BT: вимкнена (підсиленням керує телефон)"
ASB_D_BT_NOTE="(гарнітура тримає свій рівень; оберіть 'stock', якщо BT тихий)"
ASB_D_BLUR="розмиття вимкнено через system.prop (після перезавантаження)"
ASB_D_BOUNDS="device-adaptive межі: УВІМК. (OP15 — збігаються із заводським налаштуванням)"
ASB_L_MIRROR_AUDIO="скопійовано аудіо-налаштувань: %s — ASB редагує копії, а не систему"
ASB_L_MIRROR_CAMERA="скопійовано налаштувань камери: %s — ASB редагує копії, а не систему"
ASB_L_MIRROR_SYSTEM="скопійовано системних налаштувань: %s — ASB редагує копії, а не систему"
ASB_L_CAM_TUNING="Камера: налаштування зображення готове (колір, деталізація, різкість)"
ASB_L_CAM_BEAUTY="Камера: профіль ретуші готовий (налаштування за застосунками)"
ASB_L_CAM_OTHER="Камера: %s готово"
ASB_L_CAM_PREPARED="Камера: %s підготовлено зі стокової копії"
ASB_L_CAM_GRADED="Обробка камери: рівень %s застосовано до файлів: %s — насиченість, ШІ-деталізація, різкість"
ASB_L_TW_HIFI="Звук: тракт hi-fi — вендорне стиснення вимкнено, рівний еквалайзер"
ASB_L_TW_EQC="Звук: налаштовано під зовнішні еквалайзери (ViPER і подібні)"
ASB_L_TW_LOUD="Гучність: комфортний рівень досягається нижче на шкалі"
ASB_L_TW_DSP="DSP: реальне підсилення +%s дБ, з піковим лімітером"
ASB_L_TW_CAM="Камера: рівень обробки %s — колір, ШІ-деталізація й різкість підняті"
ASB_L_TW_PORTRAIT="Камера: ШІ для портретів увімкнено (у стоку вимкнений) — більше деталей на обличчях"
ASB_L_TW_VIB_OFF="Вібрація: вимкнена"
ASB_L_TW_VIB="Вібрація: рівень %s/10 за фірмовою шкалою"
ASB_L_TW_BLUR="Екран: розмиття вимкнено — менше навантаження на GPU, непрозорі підкладки"
ASB_L_TW_AUTOBAT="Батарея: при низькому заряді вмикає профіль Економія і повертається після зарядки"
ASB_L_TW_COOL="Ігри: термо-нахил вмикається раніше, телефон холодніший"
ASB_L_DSP_REG_N="зареєстровано в аудіо-конфігах: %s"
ASB_L_DSP_ODM="зареєстровано в тому конфігу, який Android справді читає"
ASB_L_CAM_QUEUED="Камера: конфігів буде підключено під час завантаження: %s"
ASB_L_MMFEED_READY="Мультимедійна телеметрія: патч готовий — за замовчуванням вимк., вмикається у WebUI (Система)"
ASB_L_CALLREC_READY="Запис дзвінків: патч готовий (файлів: %s) — за замовчуванням вимк., вмикається у WebUI (Система)"
ASB_L_VIB_SET="сила %s/10 за фірмовою шкалою, застосовано одразу"
ASB_L_VIB_TOUCH="відгук дотиків %s/10, задано окремо"
ASB_L_BAT_AUTO="при низькому заряді вмикає Економію і повертається після зарядки"
ASB_L_BAT_CHARGE="більше запасу на холодній зарядці, менше при нагріванні"
ASB_L_BAT_COOL="в іграх термо-нахил вмикається раніше, телефон холодніший"
ASB_L_MEM_TRIM="очищення фону: %s"
ASB_L_CAM_BASE_FIX1="еталон камери зі старої збірки вже був оброблений — видалено"
ASB_L_CAM_BASE_FIX2="його буде знято заново зі стокової копії після цього перезавантаження"
ASB_L_CAM_LIVE_DIRTY1="колір камери на пристрої оброблено попередньою збіркою — пропускаємо"
ASB_L_CAM_LIVE_DIRTY2="у цій установці колір камери пропущено; після перезавантаження просто встановіть ASB ще раз (вимикати не потрібно) — еталон зніметься із заводського файлу"
ASB_L_FIX_SYSSYS="видалено хибний шлях system/system від попередньої збірки"
ASB_I_OEM_KEPT="збережено поточні OEM-перемикачі"
ASB_I_PROFILE_KEPT="профіль живлення збережено"
ASB_I_PACK_CERT="пакет пристрою сертифіковано для цієї прошивки"
ASB_I_DSP_ABI="обрано ефект для цього пристрою"
ASB_I_DSP_ATTACH="під'єднувач готовий (створює ефект на загальному міксі)"
ASB_I_CAM_TUNING="налаштування камери: рівень %s, застосовано до файлів: %s"
ASB_I_RETOUCH_OK="підсумковий пакет камери перевірено"
ASB_I_HP_LIMIT="обмежувач гучності навушників знято — бережіть слух"
ASB_INSTALL_WEBUI_FIRST="Усі компоненти підготовлено; додаткові твіки залишаються стоковими."
ASB_INSTALL_WEBUI_HINT="Після перезавантаження відкрийте WebUI й увімкніть лише потрібне."
ASB_SUM_PROFILE="профіль"
ASB_SUM_NOTES="Варто прочитати"
ASB_SUM_WEBUI="Налаштування: WebUI модуля, після перезавантаження"
