#!/system/bin/sh
# =============================================================================
# asb_discover.sh — DEVICE DISCOVERY (Phase 1: facts only, writes nothing else)
# =============================================================================
# Reads what the hardware actually exposes and records it as a flat key=value
# facts file at /data/adb/asb/device_caps.env. This is pure OBSERVATION: it
# does not change any tunable, does not write to sysfs, does not touch overlays.
# It exists so that (a) asbdiag can show the real topology/back-ends, (b) future
# per-device bound synthesis has a stable, inspectable input, and (c) when a log
# arrives from a device we don't own, its capabilities are captured in the bundle.
#
# Design rule (matches the agreed architecture): capture RAW capabilities here.
# Classification ("which policy class", "which camera strategy") and synthesis
# ("derived bounds") are SEPARATE later stages that READ this file — they are not
# done here. Keeping discovery dumb and side-effect-free is what makes it safe.
# =============================================================================

ASB_DIR="/data/adb/asb"
OUT="$ASB_DIR/device_caps.env"
mkdir -p "$ASB_DIR" 2>/dev/null

_f() { cat "$1" 2>/dev/null | tr -d ' \r\n'; }
_gp() { getprop "$1" 2>/dev/null; }

{
  echo "# device_caps.env — generated by asb_discover.sh (facts only, do not edit)"
  echo "# generated_at=$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null)"

  # ---- Hardware identity ----
  echo "soc_platform=$(_gp ro.board.platform)"
  echo "soc_model=$(_gp ro.soc.model)"
  echo "codename=$(_gp ro.product.device)"
  echo "model=$(_gp ro.product.model)"
  echo "board=$(_gp ro.product.board)"
  echo "android_api=$(_gp ro.build.version.sdk)"
  echo "kernel=$(uname -r 2>/dev/null)"

  # ---- Root manager (canonical detection, single source) ----
  _rm="other"
  [ -d /data/adb/ap ]            && _rm="apatch"
  [ -d /data/adb/ksu ]           && _rm="ksu"
  [ -f /data/adb/magisk/magisk ] && _rm="magisk"
  echo "root_manager=$_rm"

  # ---- CPU topology: enumerate every cpufreq policy ----
  _pcount=0
  _plist=""
  for _pol in /sys/devices/system/cpu/cpufreq/policy*; do
    [ -d "$_pol" ] || continue
    _pid="${_pol##*policy}"
    _pcount=$((_pcount + 1))
    _plist="$_plist $_pid"
    _hwmax="$(_f "$_pol/cpuinfo_max_freq")"
    _hwmin="$(_f "$_pol/cpuinfo_min_freq")"
    _curgov="$(_f "$_pol/scaling_governor")"
    # number of frequency steps available (a proxy for table richness)
    _nfreq=0
    if [ -r "$_pol/scaling_available_frequencies" ]; then
      _nfreq=$(wc -w < "$_pol/scaling_available_frequencies" 2>/dev/null | tr -d ' ')
    fi
    echo "cpu_policy${_pid}_hwmax=$_hwmax"
    echo "cpu_policy${_pid}_hwmin=$_hwmin"
    echo "cpu_policy${_pid}_governor=$_curgov"
    echo "cpu_policy${_pid}_nfreq=$_nfreq"
  done
  echo "cpu_policy_count=$_pcount"
  echo "cpu_policy_list=$(echo "$_plist" | sed 's/^ *//')"

  # ---- GPU back-end: devfreq (freq table) vs pwrlevel vs none ----
  _gpu_backend="none"
  if [ -d /sys/class/kgsl/kgsl-3d0/devfreq ]; then
    _gpu_backend="devfreq"
    echo "gpu_devfreq_max=$(_f /sys/class/kgsl/kgsl-3d0/devfreq/max_freq)"
    echo "gpu_devfreq_min=$(_f /sys/class/kgsl/kgsl-3d0/devfreq/min_freq)"
  elif [ -r /sys/class/kgsl/kgsl-3d0/max_pwrlevel ]; then
    _gpu_backend="pwrlevel"
    echo "gpu_max_pwrlevel=$(_f /sys/class/kgsl/kgsl-3d0/max_pwrlevel)"
    echo "gpu_num_pwrlevels=$(_f /sys/class/kgsl/kgsl-3d0/num_pwrlevels)"
  fi
  echo "gpu_backend=$_gpu_backend"

  # ---- Thermal: count zones + record CPU/skin-ish sensor types ----
  _tzcount=0
  for _tz in /sys/class/thermal/thermal_zone*; do
    [ -d "$_tz" ] || continue
    _tzcount=$((_tzcount + 1))
  done
  echo "thermal_zone_count=$_tzcount"

  # ---- Subsystem path presence (which overlay/patch targets actually exist) ----
  echo "has_odm_camera_dir=$([ -d /vendor/odm/etc/camera ] || [ -d /odm/etc/camera ] && echo 1 || echo 0)"
  echo "has_vendor_audio_dir=$([ -d /vendor/etc/audio ] && echo 1 || echo 0)"
  echo "has_wlan_txqlen=$([ -e /sys/class/net/wlan0/tx_queue_len ] && echo 1 || echo 0)"
  echo "has_iw=$(command -v iw >/dev/null 2>&1 && echo 1 || echo 0)"
} > "$OUT" 2>/dev/null

chmod 0644 "$OUT" 2>/dev/null
[ -f "$OUT" ] && echo "asb_discover: wrote $OUT" || echo "asb_discover: FAILED to write $OUT"
