#!/usr/bin/env bash

set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" 2>/dev/null && pwd)"
ROOT="$(CDPATH= cd -- "$SCRIPT_DIR/.." 2>/dev/null && pwd)"
SRC="$ROOT/config/profile_bounds.conf"
OUT_SH="$ROOT/config/profile_bounds.generated.sh"
OUT_H="$ROOT/src/asb_fsm_bounds.generated.h"

if [ ! -f "$SRC" ]; then
  echo "gen_bounds: ERROR source not found: $SRC" >&2
  exit 1
fi

# shellcheck source=/dev/null
. "$SRC"

PROFILES="BATTERY BALANCED PERFORMANCE"
CLUSTERS="LITTLE BIG"

fatal() { echo "gen_bounds: ERROR $*" >&2; exit 1; }

check_range() {
  local name=$1 val=$2 lo=$3 hi=$4
  if [ -z "$val" ]; then
    fatal "$name not defined in profile_bounds.conf"
  fi
  if [ "$val" -lt "$lo" ] || [ "$val" -gt "$hi" ]; then
    fatal "$name=$val out of range [$lo..$hi]"
  fi
}

check_le() {
  local lhs_n=$1 lhs_v=$2 rhs_n=$3 rhs_v=$4
  if [ "$lhs_v" -gt "$rhs_v" ]; then
    fatal "invariant violated: $lhs_n=$lhs_v > $rhs_n=$rhs_v"
  fi
}

for P in $PROFILES; do
  for C in $CLUSTERS; do
    eval "min=\$${P}_CPU_MIN_${C}"
    eval "cap=\$${P}_CPU_CAP_${C}"
    eval "max=\$${P}_CPU_MAX_${C}"
    check_le "${P}_CPU_MIN_${C}" "$min" "${P}_CPU_CAP_${C}" "$cap"
    check_le "${P}_CPU_CAP_${C}" "$cap" "${P}_CPU_MAX_${C}" "$max"
  done
  eval "gmp=\$${P}_GPU_MAX_PCT"
  eval "fgmp=\$${P}_FLOOR_GPU_MAX_PCT"
  eval "fgnp=\$${P}_FLOOR_GPU_MIN_PCT"
  eval "cgnp=\$${P}_CEIL_GPU_MIN_PCT"
  eval "frt=\$${P}_FLOOR_RAVG_TICKS"
  eval "crt=\$${P}_CEIL_RAVG_TICKS"
  eval "fie=\$${P}_FLOOR_IDLE_ENOUGH"
  eval "cie=\$${P}_CEIL_IDLE_ENOUGH"
  eval "fut=\$${P}_FLOOR_UCLAMP_TOP"
  eval "fub=\$${P}_FLOOR_UCLAMP_BG"
  eval "cut=\$${P}_CEIL_UCLAMP_TOP"
  eval "cub=\$${P}_CEIL_UCLAMP_BG"

  check_range "${P}_GPU_MAX_PCT"        "$gmp"  1 100
  check_range "${P}_FLOOR_GPU_MAX_PCT"  "$fgmp" 1 100
  check_range "${P}_FLOOR_GPU_MIN_PCT"  "$fgnp" 0 100
  check_range "${P}_CEIL_GPU_MIN_PCT"   "$cgnp" 0 100
  check_le    "${P}_FLOOR_GPU_MAX_PCT"  "$fgmp" "${P}_GPU_MAX_PCT" "$gmp"
  check_range "${P}_FLOOR_RAVG_TICKS"   "$frt"  1 1000
  check_range "${P}_CEIL_RAVG_TICKS"    "$crt"  1 1000
  check_range "${P}_FLOOR_IDLE_ENOUGH"  "$fie"  0 100
  check_range "${P}_CEIL_IDLE_ENOUGH"   "$cie"  0 100
  check_range "${P}_FLOOR_UCLAMP_TOP"   "$fut"  0 100
  check_range "${P}_FLOOR_UCLAMP_BG"    "$fub"  0 100
  check_range "${P}_CEIL_UCLAMP_TOP"    "$cut"  0 100
  check_range "${P}_CEIL_UCLAMP_BG"     "$cub"  0 100
  check_le    "${P}_FLOOR_UCLAMP_TOP"   "$fut"  "${P}_CEIL_UCLAMP_TOP" "$cut"
done

for C in $CLUSTERS; do
  eval "bat=\$BATTERY_CPU_CAP_${C}"
  eval "bal=\$BALANCED_CPU_CAP_${C}"
  eval "per=\$PERFORMANCE_CPU_CAP_${C}"
  check_le "BATTERY_CPU_CAP_${C}"  "$bat" "BALANCED_CPU_CAP_${C}"    "$bal"
  check_le "BALANCED_CPU_CAP_${C}" "$bal" "PERFORMANCE_CPU_CAP_${C}" "$per"
done

tmp_sh="${OUT_SH}.tmp.$$"
tmp_h="${OUT_H}.tmp.$$"
trap 'rm -f "$tmp_sh" "$tmp_h"' EXIT

{
  printf '# AutoSystemBoost — auto-generated by tools/gen_bounds.sh. DO NOT EDIT.\n'
  printf '# Source: config/profile_bounds.conf\n'
  printf '#\n'
  printf '# Consumers: profiles/{battery,balanced,performance}.sh source this file\n'
  printf '# and read variables matching their own profile prefix.\n\n'
  for P in $PROFILES; do
    for K in CPU_MIN_LITTLE CPU_MIN_BIG CPU_CAP_LITTLE CPU_CAP_BIG \
             CPU_MAX_LITTLE CPU_MAX_BIG GPU_MAX_PCT; do
      eval "v=\$${P}_${K}"
      printf '%s_%s=%s\n' "$P" "$K" "$v"
    done
    printf '\n'
  done
} > "$tmp_sh"

{
  printf '/*\n'
  printf ' * AutoSystemBoost — auto-generated by tools/gen_bounds.sh. DO NOT EDIT.\n'
  printf ' * Source: config/profile_bounds.conf\n'
  printf ' *\n'
  printf ' * Included by src/asb_fsm.h to define g_profile_bounds[] without hand-edited\n'
  printf ' * numerics. Every macro maps 1:1 to one initializer field.\n'
  printf ' */\n'
  printf '#ifndef ASB_FSM_BOUNDS_GENERATED_H\n'
  printf '#define ASB_FSM_BOUNDS_GENERATED_H\n\n'

  for P in $PROFILES; do
    eval "cap_l=\$${P}_CPU_CAP_LITTLE"
    eval "cap_b=\$${P}_CPU_CAP_BIG"
    eval "min_l=\$${P}_CPU_MIN_LITTLE"
    eval "min_b=\$${P}_CPU_MIN_BIG"
    eval "max_l=\$${P}_CPU_MAX_LITTLE"
    eval "max_b=\$${P}_CPU_MAX_BIG"
    eval "gmp=\$${P}_GPU_MAX_PCT"
    eval "fgmp=\$${P}_FLOOR_GPU_MAX_PCT"
    eval "fgnp=\$${P}_FLOOR_GPU_MIN_PCT"
    eval "cgnp=\$${P}_CEIL_GPU_MIN_PCT"
    eval "frt=\$${P}_FLOOR_RAVG_TICKS"
    eval "crt=\$${P}_CEIL_RAVG_TICKS"
    eval "fie=\$${P}_FLOOR_IDLE_ENOUGH"
    eval "cie=\$${P}_CEIL_IDLE_ENOUGH"
    eval "fut=\$${P}_FLOOR_UCLAMP_TOP"
    eval "fub=\$${P}_FLOOR_UCLAMP_BG"
    eval "cut=\$${P}_CEIL_UCLAMP_TOP"
    eval "cub=\$${P}_CEIL_UCLAMP_BG"

    printf '/* %s — derived from profile_bounds.conf */\n' "$P"
    printf '#define ASB_%s_FLOOR_CPU_MAX_LITTLE %s\n' "$P" "$cap_l"
    printf '#define ASB_%s_FLOOR_CPU_MAX_BIG    %s\n' "$P" "$cap_b"
    printf '#define ASB_%s_FLOOR_CPU_MIN_LITTLE %s\n' "$P" "$min_l"
    printf '#define ASB_%s_FLOOR_CPU_MIN_BIG    %s\n' "$P" "$min_b"
    printf '#define ASB_%s_CEIL_CPU_MAX_LITTLE  %s\n' "$P" "$max_l"
    printf '#define ASB_%s_CEIL_CPU_MAX_BIG     %s\n' "$P" "$max_b"
    printf '#define ASB_%s_CEIL_CPU_MIN_LITTLE  %s\n' "$P" "$cap_l"
    printf '#define ASB_%s_CEIL_CPU_MIN_BIG     %s\n' "$P" "$cap_b"
    printf '#define ASB_%s_FLOOR_GPU_MAX_PCT    %s\n' "$P" "$fgmp"
    printf '#define ASB_%s_FLOOR_GPU_MIN_PCT    %s\n' "$P" "$fgnp"
    printf '#define ASB_%s_CEIL_GPU_MAX_PCT     %s\n' "$P" "$gmp"
    printf '#define ASB_%s_CEIL_GPU_MIN_PCT     %s\n' "$P" "$cgnp"
    printf '#define ASB_%s_FLOOR_RAVG_TICKS     %s\n' "$P" "$frt"
    printf '#define ASB_%s_CEIL_RAVG_TICKS      %s\n' "$P" "$crt"
    printf '#define ASB_%s_FLOOR_IDLE_ENOUGH    %s\n' "$P" "$fie"
    printf '#define ASB_%s_CEIL_IDLE_ENOUGH     %s\n' "$P" "$cie"
    printf '#define ASB_%s_FLOOR_UCLAMP_TOP     %s\n' "$P" "$fut"
    printf '#define ASB_%s_FLOOR_UCLAMP_BG      %s\n' "$P" "$fub"
    printf '#define ASB_%s_CEIL_UCLAMP_TOP      %s\n' "$P" "$cut"
    printf '#define ASB_%s_CEIL_UCLAMP_BG       %s\n' "$P" "$cub"
    printf '\n'
  done

  printf '#endif /* ASB_FSM_BOUNDS_GENERATED_H */\n'
} > "$tmp_h"

sh_changed=0
h_changed=0
if [ ! -f "$OUT_SH" ] || ! cmp -s "$tmp_sh" "$OUT_SH"; then
  mv "$tmp_sh" "$OUT_SH"
  sh_changed=1
else
  rm -f "$tmp_sh"
fi
if [ ! -f "$OUT_H" ] || ! cmp -s "$tmp_h" "$OUT_H"; then
  mv "$tmp_h" "$OUT_H"
  h_changed=1
else
  rm -f "$tmp_h"
fi
trap - EXIT

if [ "$sh_changed" -eq 1 ] || [ "$h_changed" -eq 1 ]; then
  echo "gen_bounds: regenerated ($([ $sh_changed -eq 1 ] && echo "sh ")$([ $h_changed -eq 1 ] && echo "h"))"
else
  echo "gen_bounds: up-to-date"
fi
exit 0
