#ifndef ASB_FSM_BOUNDS_GENERATED_H
#define ASB_FSM_BOUNDS_GENERATED_H

/* BATTERY */
#define ASB_BATTERY_FLOOR_CPU_MAX_LITTLE 921600
#define ASB_BATTERY_FLOOR_CPU_MAX_BIG    921600
#define ASB_BATTERY_FLOOR_CPU_MIN_LITTLE 307200
#define ASB_BATTERY_FLOOR_CPU_MIN_BIG    614400
#define ASB_BATTERY_CEIL_CPU_MAX_LITTLE  1804800
#define ASB_BATTERY_CEIL_CPU_MAX_BIG     2208000
#define ASB_BATTERY_CEIL_CPU_MIN_LITTLE  921600
#define ASB_BATTERY_CEIL_CPU_MIN_BIG     921600
#define ASB_BATTERY_FLOOR_GPU_MAX_PCT    45
#define ASB_BATTERY_FLOOR_GPU_MIN_PCT    0
#define ASB_BATTERY_CEIL_GPU_MAX_PCT     50
#define ASB_BATTERY_CEIL_GPU_MIN_PCT     0
#define ASB_BATTERY_FLOOR_RAVG_TICKS     8
#define ASB_BATTERY_CEIL_RAVG_TICKS      8
#define ASB_BATTERY_FLOOR_IDLE_ENOUGH    95
#define ASB_BATTERY_CEIL_IDLE_ENOUGH     95
#define ASB_BATTERY_FLOOR_UCLAMP_TOP     35
#define ASB_BATTERY_FLOOR_UCLAMP_BG      25
#define ASB_BATTERY_CEIL_UCLAMP_TOP      50
#define ASB_BATTERY_CEIL_UCLAMP_BG       40

/* BALANCED */
#define ASB_BALANCED_FLOOR_CPU_MAX_LITTLE 1190400
#define ASB_BALANCED_FLOOR_CPU_MAX_BIG    1881600
#define ASB_BALANCED_FLOOR_CPU_MIN_LITTLE 787200
#define ASB_BALANCED_FLOOR_CPU_MIN_BIG    883200
#define ASB_BALANCED_CEIL_CPU_MAX_LITTLE  3302400
#define ASB_BALANCED_CEIL_CPU_MAX_BIG     3974400
#define ASB_BALANCED_CEIL_CPU_MIN_LITTLE  1190400
#define ASB_BALANCED_CEIL_CPU_MIN_BIG     1881600
#define ASB_BALANCED_FLOOR_GPU_MAX_PCT    42
#define ASB_BALANCED_FLOOR_GPU_MIN_PCT    0
#define ASB_BALANCED_CEIL_GPU_MAX_PCT     85
#define ASB_BALANCED_CEIL_GPU_MIN_PCT     0
#define ASB_BALANCED_FLOOR_RAVG_TICKS     4
#define ASB_BALANCED_CEIL_RAVG_TICKS      3
#define ASB_BALANCED_FLOOR_IDLE_ENOUGH    50
#define ASB_BALANCED_CEIL_IDLE_ENOUGH     45
#define ASB_BALANCED_FLOOR_UCLAMP_TOP     50
#define ASB_BALANCED_FLOOR_UCLAMP_BG      25
#define ASB_BALANCED_CEIL_UCLAMP_TOP      85
#define ASB_BALANCED_CEIL_UCLAMP_BG       35

/* PERFORMANCE */
#define ASB_PERFORMANCE_FLOOR_CPU_MAX_LITTLE 2150400
#define ASB_PERFORMANCE_FLOOR_CPU_MAX_BIG    2342400
#define ASB_PERFORMANCE_FLOOR_CPU_MIN_LITTLE 1190400
#define ASB_PERFORMANCE_FLOOR_CPU_MIN_BIG    921600
#define ASB_PERFORMANCE_CEIL_CPU_MAX_LITTLE  2956800
#define ASB_PERFORMANCE_CEIL_CPU_MAX_BIG     3302400
#define ASB_PERFORMANCE_CEIL_CPU_MIN_LITTLE  2150400
#define ASB_PERFORMANCE_CEIL_CPU_MIN_BIG     2342400
#define ASB_PERFORMANCE_FLOOR_GPU_MAX_PCT    35
#define ASB_PERFORMANCE_FLOOR_GPU_MIN_PCT    8
#define ASB_PERFORMANCE_CEIL_GPU_MAX_PCT     50
#define ASB_PERFORMANCE_CEIL_GPU_MIN_PCT     20
#define ASB_PERFORMANCE_FLOOR_RAVG_TICKS     2
#define ASB_PERFORMANCE_CEIL_RAVG_TICKS      2
#define ASB_PERFORMANCE_FLOOR_IDLE_ENOUGH    10
#define ASB_PERFORMANCE_CEIL_IDLE_ENOUGH     8
#define ASB_PERFORMANCE_FLOOR_UCLAMP_TOP     68
#define ASB_PERFORMANCE_FLOOR_UCLAMP_BG      35
#define ASB_PERFORMANCE_CEIL_UCLAMP_TOP      84
#define ASB_PERFORMANCE_CEIL_UCLAMP_BG       62

#endif /* ASB_FSM_BOUNDS_GENERATED_H */
